### ISSUE TITLE
regression: salt-bootstrap stable no longer installs libzmq3

### ISSUE THREAD

**Issue by timcharper** [saltstack/salt-bootstrap#688] opened 2015-11-06 04:33 UTC
I installed saltmaster via the following command on `Debian Jessie 8`:

```
sudo sh install_salt.sh -M -L -P git v2015.8.1
```

It reported success. However, 0mq didn't install properly:

```
$ salt-key
Traceback (most recent call last):
  File "/usr/bin/salt-key", line 10, in <module>
    salt_key()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 285, in salt_key
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/key.py", line 30, in run
    key = salt.key.KeyCLI(self.config)
  File "/usr/lib/python2.7/dist-packages/salt/key.py", line 54, in __init__
    self.key = Key(opts)
  File "/usr/lib/python2.7/dist-packages/salt/key.py", line 522, in __init__
    listen=False)
  File "/usr/lib/python2.7/dist-packages/salt/utils/event.py", line 126, in get_event
    return MasterEvent(sock_dir, opts, listen=listen)
  File "/usr/lib/python2.7/dist-packages/salt/utils/event.py", line 677, in __init__
    super(MasterEvent, self).__init__('master', sock_dir, opts, listen=listen)
  File "/usr/lib/python2.7/dist-packages/salt/utils/event.py", line 178, in __init__
    self.context = zmq.Context()
NameError: global name 'zmq' is not defined
```

I reverted back to an earlier `install_salt.sh` script I'd downloaded, `Oct 29 16:07` (UTC), with md5sum `013273b3abbfe22798ba1b611669c0f9`, and was able to install successfully. This script was working properly at this point in time.

I'm betting this merge introduced the breaking change: https://github.com/saltstack/salt-bootstrap/commit/29fc62f9bdbc861ffdcbca0374e8f9d7218da5ab

**Comment by jfindlay** [comment] 2015-11-11 23:42
Thanks for the report, @timcharper.

**Comment by timcharper** [comment] 2015-11-18 03:50
@jfindlay FYI If I simply run `apt-get install -y python-zmq` on the bootstrapped instance, then everything works fine.

**Comment by timcharper** [comment] 2015-11-18 03:59
`python-apt` was also missing; is it because I specified to use PIP dependencies, and none of the PIP dependencies installed?

**Comment by jfindlay** [comment] 2015-11-19 15:57
I looked over the source and I wouldn't be surprised if this is what happens.

**Comment by wolfpackmars2** [comment] 2015-12-04 07:29
I was reviewing the debian bootstrap code and found a potential problem.  I've suggested a pull request which I believe will fix this problem.

If I'm right, the problem is with line 2394 of the current bootstrap script.

**Comment by wolfpackmars2** [comment] 2015-12-07 09:45
@timcharper my changes have been merged with the latest copy of the bootstrap - see if that has resolved the problem you were seeing.

Also, make sure you are referencing the development copy of the script.  bootstrap.saltstack.org currently references the stable version of the bootstrap, which doesn't include the dependency fix.

**Comment by s0undt3ch** [comment] 2015-12-07 10:17
If you pass `/develop` you should get the develop version....
And, if that one isn't up to date, the GitHub raw link always is...

**Comment by wolfpackmars2** [comment] 2015-12-07 10:17
The development version currently fails when trying to install libzmq3-dev

Output:

pciutils is already the newest version.
procps is already the newest version.
python-apt is already the newest version.
python-zmq is already the newest version.
python-zmq set to manually installed.
libzmq3 is already the newest version.
libzmq3 set to manually installed.
python-requests is already the newest version.
The following NEW packages will be installed:
  libzmq3-dev
0 upgraded, 1 newly installed, 0 to remove and 57 not upgraded.
Need to get 564 kB of archives.
After this operation, 1,644 kB of additional disk space will be used.
Get:1 http://repo.saltstack.com/apt/debian/latest/ jessie/main libzmq3-dev amd64 4.0.5+dfsg-3 [564 kB]
Fetched 564 kB in 0s (1,309 kB/s)
E: Failed to fetch http://repo.saltstack.com/apt/debian/latest/pool/main/z/zeromq3/libzmq3-dev_4.0.5+dfsg-3_amd64.deb  Size mismatch

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
- ERROR: Failed to run install_debian_8_deps()!!!

Although I believe this is a separate issue related to the package in the repository.  Using the packaged version of salt-minion works without the -dev package, but it may be required for the GIT development version of salt.  If the -dev package isn't needed, it should be removed from the bootstrap script.  Or the package should be reviewed and fixed if necessary.  There seems to be some upheaval in the package repositories atm, so I expect this to resolve itself _at some point_.

**Comment by timcharper** [comment] 2015-12-08 00:53
I just tried, got this failure:

```
E: Failed to fetch http://repo.saltstack.com/apt/debian/latest/pool/main/z/zeromq3/libzmq3-dev_4.0.5+dfsg-3_amd64.deb  Size mismatch
```

**Comment by vutny** [comment] 2015-12-25 11:31
@timcharper Looks like it was fixed.

```
$ curl -L http://repo.saltstack.com/apt/debian/latest/pool/main/z/zeromq3/libzmq3-dev_4.0.5+dfsg-3_amd64.deb -o /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  550k  100  550k    0     0   348k      0  0:00:01  0:00:01 --:--:--  347k
```

I think the issue should be closed.

**Comment by timcharper** [comment] 2015-12-28 16:16
It was! Working now on my end. Thank you!

**Closed as completed** 2015-12-28 16:16 UTC
