### ISSUE TITLE
Salt-Cloud bootstrap to RHEL7 in AWS fails (GPG Keys)

### ISSUE THREAD

**Issue by yamamushi** [saltstack/salt-bootstrap#757] opened 2016-02-10 17:32 UTC
I don't know if this is related to #724 , however it does look related to https://github.com/saltstack/salt/issues/29094 . 

It was suggested that an issue be opened here, so I apologize if this is really just a duplicate of #724 

Using salt-cloud to spin up a new RHEL7 instance in AWS results in the following error: 

```
Downloading packages:
warning: /var/cache/yum/x86_64/7ServeConnection to 172.31.9.52 closed.
r/repo-saltstack-el7/packages/pciutils-3.2.1-4.el7.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY
Public key for pciutils-3.2.1-4.el7.x86_64.rpm is not installed
--------------------------------------------------------------------------------
Total                                              8.1 MB/s | 6.0 MB  00:00
Retrieving key from https://repo.saltstack.com/yum/rhel7/SALTSTACK-GPG-KEY.pub


The GPG keys listed for the "SaltStack EL7 Repo" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.


 Failing package is: pciutils-3.2.1-4.el7.x86_64
 GPG Keys are configured as: https://repo.saltstack.com/yum/rhel7/SALTSTACK-GPG-KEY.pub

 * ERROR: Failed to run install_red_hat_enterprise_linux_stable()!!!
Error: There was a profile error: Command 'ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oKbdInteractiveAuthentication=no -i /etc/salt/minion_key.pem -p 22 ec2-user@172.31.9.52 \'sudo /tmp/.saltcloud-aeb7b201-5f9a-4625-923c-8456ace1f24c/deploy.sh -c \'"\'"\'/tmp/.saltcloud-aeb7b201-5f9a-4625-923c-8456ace1f24c\'"\'"\'\'' failed. Exit code: 1
```

I've seen several workarounds suggested for people who are manually setting up their minions, however I'm unsure as to how to apply one of these workarounds through the salt-cloud workflow. 

I'm happy to try any suggestions.

**Comment by dmurphy18** [comment] 2016-02-10 18:03
@yamamushi Please use https://repo.saltstack.com/yum/redhat/7/x86_64/SALTSTACK-GPG-KEY.pub
and http://repo.saltstack.com/yum/redhat/7/x86_64/latest/base/RPM-GPG-KEY-CentOS-7

The pciutils are located in the base sub-directory, hence the correct key for these is RPM-GPG-KEY-CentOS-7.  The packages in the base sub-directory are provided as a convenience for those installations which disable updates, extras or EPEL repositories, or do not provide all of the original OS repository packages.

The preferred format for using repo.saltstack.com is :
OS release version / base architecture / latest
or if pinning to a particular version of salt:
OS release version / base architecture / archive / salt version

Also the instructions on http://repo.saltstack.com/#rhel provide a rpm package which will install the appropriate keys and repo file for Redhat.

**Comment by yamamushi** [comment] 2016-02-10 19:02
@dmurphy18 We can't use the rpm packages for installing salt, as there is an issue that prevents Windows R2 Instances from being configured properly (in AWS) that has only been resolved through the bootstrap installation method.

https://github.com/saltstack/salt/issues/30167

Perhaps when a new RPM is available the issue will be resolved.

How would I go about using that GPG key through salt-cloud? As far as I understand, salt-cloud is just provisioning using the bootstrap script, and using the new GPG key would require manually configuring the instances we're creating rather than automatically configuring them through salt-cloud.

**Comment by dmurphy18** [comment] 2016-02-10 21:00
@yamamushi have update your bootstrap script with a 'salt-cloud -u' ?

Note, there is work being done for win.exe for RH7 by a contributor, which should help with this issue, win.exe for RH 6 is available since 2015.8.5.  It was added to the repo.saltstack.com to address Windows R2 issues with AWS, unfortunately time ran out on getting RH 7 to work before the point release.

**Comment by yamamushi** [comment] 2016-02-10 21:08
@dmurphy18 , I've tried updating with 'salt-cloud -u' but I get the same issues as I reported above :-/ 

I was hoping there was a flag or a config change I could pass in to get around the problem, but a look through the salt-cloud documentation doesn't mention anything obvious I could try to get around the issue.

**Comment by vutny** [comment] 2016-02-23 08:12
Hi @yamamushi 
This issue is probably a duplicate of saltstack/salt#31193

**Comment by vutny** [comment] 2016-02-26 14:41
@yamamushi This is already fixed in latest `develop`.
Just download https://github.com/saltstack/salt-bootstrap/raw/develop/bootstrap-salt.sh to `/etc/salt/cloud.deploy.d/bootstrap-salt.sh` and everything should be good.

I think this issue could be closed. Thanks!

**Comment by yamamushi** [comment] 2016-02-26 15:33
@vutny Using the develop branch is exactly what SaltStack support told our organization not to do, so we will have to wait for the fixes to be merged into a stable branch hopefully sometime in the near future.

**Comment by vutny** [comment] 2016-02-26 15:51
@yamamushi That's maybe true for the whole saltstack/salt project, but I can assure you that current `develop` version of `bootstrap-salt.sh` script is actually far more stable than `stable` branch :smile: There are tons of fixes merged recently. Anyhow, I'm looking forward for real `stable` version to be produced.

**Comment by vutny** [comment] 2016-03-01 15:30
@yamamushi @dmurphy18 I guess this issue is resolved and should be closed.

**Comment by yamamushi** [comment] 2016-03-01 16:25
What is the ETA for the develop branch being merged into stable and pushed up to https://bootstrap.saltstack.com ?

**Comment by vutny** [comment] 2016-03-02 08:45
All of us are looking forward to that moment!

**Comment by cro** [comment] 2016-03-02 15:44
We typically try to cut a new release whenever we release a new version of Salt.  We're getting ready to cut release candidates of 2016.3 now, so an updated bootstrap should be forthcoming in March.

I'm going to close this ticket, feel free to comment and we can re-open if needed.

**Closed as completed by cro** 2016-03-02 15:44 UTC
