### ISSUE TITLE
SSL errors installing from bootstrap

### ISSUE THREAD

**Issue by ghost** [saltstack/salt-bootstrap#462] opened 2014-09-08 21:26 UTC
Seeing the same error when installing on multiple distros (CentOS, SUSE, so far):

```
# wget -O - http://bootstrap.saltstack.org
--2014-09-08 17:15:12--  http://bootstrap.saltstack.org/
Resolving bootstrap.saltstack.org... 74.208.29.198
Connecting to bootstrap.saltstack.org|74.208.29.198|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.github.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh [following]
--2014-09-08 17:15:13--  https://raw.github.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh
Resolving raw.github.com... 23.235.47.133
Connecting to raw.github.com|23.235.47.133|:443... connected.
ERROR: certificate common name `www.github.com' doesn't match requested host name `raw.github.com'.
To connect to raw.github.com insecurely, use `--no-check-certificate'.
Unable to establish SSL connection.
```

**Comment by whiteinge** [comment] 2014-09-09 00:15
I vaguely recall this being related to an older version of wget. @s0undt3ch do you remember for sure?

**Comment by s0undt3ch** [comment] 2014-09-09 13:20
There are some issues with wget and fetch, mostly older ca-certs, but, this report is about an http(not https). Didn't we decided to kill the http redirect? If we want to preserve it, we should probably first redirect to our https, then, github?

**Comment by gtmanfred** [comment] 2014-09-09 13:22
It doesn't matter how you do it, if you redirect to github and they are
using the old version of ca-certs it will fail.

**Comment by gtmanfred** [comment] 2014-09-09 15:35
This is not a bug, usually I see this on rhel 5.6, because the openssl package is old and doesn't have the new CA certificate bundle that github has their key signed by.  They need to update.  Your other option would be to put it on the server where the bootstrap.saltstack.org redirect lives, and just server it out yourself (could use webhooks and the reactor to deploy it when you do a git push for develop, or tag for the stable version)

**Comment by s0undt3ch** [comment] 2014-09-09 17:05
On September 9, 2014 4:35:29 PM GMT+01:00, Daniel Wallace notifications@github.com wrote:

> This is not a bug, usually I see this on rhel 5.6, because the openssl
> package is old and doesn't have the new CA certificate bundle that
> github has their key signed by.  They need to update.  Your other
> option would be to put it on the server where the
> bootstrap.saltstack.org redirect lives, and just server it out yourself
> (could use webhooks and the reactor to deploy it when you do a git push
> for develop, or tag for the stable version)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/saltstack/salt-bootstrap/issues/462#issuecomment-54988064

My thoughts exactly. I need to check with @SaltStack on that possibility. A bit while back we considered this but at that time it was not the best choice.
Pedro Algarvio @ Phone

**Comment by whiteinge** [comment] 2014-09-11 03:53
@s0undt3ch do you remember why we didn't host ourselves? (I can't remember.
It might have been that we didn't have a SSL cert back then.)

I'd be fine with setting that up now.

**Comment by ghost** [comment] 2014-10-20 20:11
Any movement or further thoughts on this?

**Comment by gtmanfred** [comment] 2014-10-20 21:03
@alexthegraham this should work fine if you are on a supported distribution.

What are you running on? and what version of openssl or ca-certificates do you have installed?

The only times I was running into this issue was back on rhel 5.6, before updating it to 5.10

**Comment by ghost** [comment] 2014-10-21 23:41
Per above, updating openssl works just fine to get this going again, it just means that there's additional work to be done before salting minions running on older OS's. Not a big deal, but I kinda figured you might want to reduce your reliance on GitHub's SSL either way. If you're not planning to make this change, go ahead and close the request.

**Comment by whiteinge** [comment] 2014-10-22 13:55
Thanks for verifying!

We'll make the switch to self hosting soon as I or someone find some spare
cycles.

That said, it's possible that our SSL certificate will be in the same boat
as GitHub's certificate and won't work with the expired (?) OpenSSL CA
bundle in old Cent 5. Needs to be tested in any case.

**Comment by wolfpackmars2** [comment] 2015-12-07 10:53
Another option, if there is a package that can be installed on Centos5 that resolves this (but isn't part of the official cent5 repos?) then the bootstrap can be updated to install that dependency for Cent5 distributions.

**Comment by vutny** [comment] 2015-12-24 09:32
@wolfpackmars2 

```
$ rpm -qf /etc/pki/tls/certs/ca-bundle.crt
openssl-0.9.8e-32.el5_11
```

You just need to keep `openssl` up-to-date. But sometimes it is not very "fresh"...
If you need to get lastet CA bundle here and now, this is a dirty way:

```
# cd /etc/pki/tls/certs
# cp ca-bundle.crt ca-bundle.crt.rpmsave
# curl -4 http://curl.haxx.se/ca/cacert.pem -o ca-bundle.crt
```

I think this issue could be closed.

**Comment by vutny** [comment] 2016-01-27 11:53
@alexthegraham, @jfindlay this seems like not a bootstrap issue and could be closed.

**Comment by jfindlay** [comment] 2016-01-29 22:45
Also, bootstrap is hosted at https://bootstrap.saltstack.com/ (whereas http://bootstrap.saltstack.org still redirects to github).

**Closed as completed by jfindlay** 2016-01-29 22:45 UTC
Labels: Bug, Question
