### ISSUE TITLE
bootstrap.sh v2024.11.21 error "No dependencies installation function found" v2024.11.07 still works fine

### ISSUE THREAD

**Issue by corosou** [saltstack/salt-bootstrap#2050] opened 2024-11-22 16:54 UTC
### Description of Issue/Question

bootstrap.sh v2024.11.21 is giving an error "No dependencies installation function found"
bootstrap.sh v2024.11.07 works just fine

### Setup

AlmaLinux 9.5

### Steps to Reproduce Issue

sh bootstrap-salt.sh -D
 *  INFO: Running version: 2024.11.21
 *  INFO: Executed by: sh
 *  INFO: Command line: 'bootstrap-salt.sh -D'

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   5.14.0-503.14.1.el9_5.x86_64
 *  INFO:   Distribution: AlmaLinux 9.5

 * DEBUG: Binaries will be searched using the following $PATH: /root/.local/bin:/root/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin
 *  INFO: Installing minion
 * DEBUG: install_almalinux_9_onedir_deps not found....
 * DEBUG: install_almalinux_9_5_onedir_deps not found....
 * DEBUG: install_almalinux_9_deps not found....
 * DEBUG: install_almalinux_9_5_deps not found....
 * DEBUG: install_almalinux_onedir_deps not found....
 * DEBUG: install_almalinux_deps not found....
 * DEBUG: DEPS_INSTALL_FUNC=null
 * DEBUG: config_almalinux_9_onedir_salt not found....
 * DEBUG: config_almalinux_9_5_onedir_salt not found....
 * DEBUG: config_almalinux_9_salt not found....
 * DEBUG: config_almalinux_9_5_salt not found....
 * DEBUG: config_almalinux_onedir_salt not found....
 * DEBUG: config_almalinux_salt not found....
 *  INFO: Found function config_salt
 * DEBUG: CONFIG_SALT_FUNC=config_salt
 * DEBUG: preseed_almalinux_9_onedir_master not found....
 * DEBUG: preseed_almalinux_9_5_onedir_master not found....
 * DEBUG: preseed_almalinux_9_master not found....
 * DEBUG: preseed_almalinux_9_5_master not found....
 * DEBUG: preseed_almalinux_onedir_master not found....
 * DEBUG: preseed_almalinux_master not found....
 *  INFO: Found function preseed_master
 * DEBUG: PRESEED_MASTER_FUNC=preseed_master
 * DEBUG: INSTALL_FUNC_NAMES=install_almalinux_9_onedir install_almalinux_9_5_onedir install_almalinux_onedir
 * DEBUG: install_almalinux_9_onedir not found....
 * DEBUG: install_almalinux_9_5_onedir not found....
 * DEBUG: install_almalinux_onedir not found....
 * DEBUG: INSTALL_FUNC=null
 * DEBUG: install_almalinux_9_onedir_post not found....
 * DEBUG: install_almalinux_9_5_onedir_post not found....
 * DEBUG: install_almalinux_9_post not found....
 * DEBUG: install_almalinux_9_5_post not found....
 * DEBUG: install_almalinux_onedir_post not found....
 * DEBUG: install_almalinux_post not found....
 * DEBUG: POST_INSTALL_FUNC=null
 * DEBUG: install_almalinux_9_onedir_restart_daemons not found....
 * DEBUG: install_almalinux_9_5_onedir_restart_daemons not found....
 * DEBUG: install_almalinux_9_restart_daemons not found....
 * DEBUG: install_almalinux_9_5_restart_daemons not found....
 * DEBUG: install_almalinux_onedir_restart_daemons not found....
 * DEBUG: install_almalinux_restart_daemons not found....
 * DEBUG: STARTDAEMONS_INSTALL_FUNC=null
 * DEBUG: daemons_running_almalinux_9_onedir not found....
 * DEBUG: daemons_running_almalinux_9_5_onedir not found....
 * DEBUG: daemons_running_almalinux_9 not found....
 * DEBUG: daemons_running_almalinux_9_5 not found....
 * DEBUG: daemons_running_almalinux_onedir not found....
 * DEBUG: daemons_running_almalinux not found....
 *  INFO: Found function daemons_running_onedir
 * DEBUG: DAEMONS_RUNNING_FUNC=daemons_running_onedir
 * DEBUG: install_almalinux_9_onedir_check_services not found....
 * DEBUG: install_almalinux_9_5_onedir_check_services not found....
 * DEBUG: install_almalinux_9_check_services not found....
 * DEBUG: install_almalinux_9_5_check_services not found....
 * DEBUG: install_almalinux_onedir_check_services not found....
 * DEBUG: install_almalinux_check_services not found....
 * DEBUG: CHECK_SERVICES_FUNC=null
 * ERROR: No dependencies installation function found. Exiting...
 * DEBUG: Removing the logging pipe /tmp/bootstrap-salt.logpipe
 * DEBUG: Removing the temporary apt error file /tmp/apt_error.ChbYHl

### Versions and Systems

sh bootstrap-salt.sh -v
bootstrap-salt.sh -- Version 2024.11.21

**Comment by dmurphy18** [comment] 2024-11-25 18:12
Closing this since duplicate of https://github.com/saltstack/salt-bootstrap/issues/2053, which resolves the issue with an upgrade of pip from default 21.3.1 to 24.3.1

**Closed as completed by dmurphy18** 2024-11-25 18:12 UTC
Labels: Duplicate
