### ISSUE TITLE
Docker + salt-bootstrap failure

### ISSUE THREAD

**Issue by JasonSwindle** [saltstack/salt-bootstrap#394] opened 2014-05-14 23:31 UTC
Howdy,

I am trying to use salt-bootstrap inside of a docker container and I keep getting the following error

```
Processing triggers for ureadahead (0.100.0-16) ...
 *  INFO: Running install_ubuntu_check_services()
 * ERROR: Failed to run install_ubuntu_check_services()!!!
2014/05/14 23:28:24 The command [/bin/sh -c curl -L http://bootstrap.saltstack.org -o install_salt.sh && sh install_salt.sh -M -N -X] returned a non-zero code: 1
```

``` Dockerfile
FROM ubuntu:14.04

MAINTAINER Jason Swindle

ENV DEBIAN_FRONTEND noninteractive
ENV TERM linux

## Update the apt database
RUN apt-get update

## Upgrade any packages
RUN apt-get upgrade -y

## Install what we need
RUN apt-get install -y sudo openssh-server curl python-pip

## Install supervisor
RUN pip install supervisor

## Install Salt Master (of Masters)
RUN curl -L http://bootstrap.saltstack.org -o install_salt.sh && sh install_salt.sh -M -N -X

## Remove the apt database
RUN apt-get clean

## Set root's password
RUN echo 'root:fakepassword' | chpasswd

## Make the SSH dir
RUN mkdir /var/run/sshd 

## Make Salt-Master a service
ADD ./salt.conf /etc/supervisor/conf.d/

## Make sshD a service
ADD ./ssh.conf /etc/supervisor/conf.d/

## Not sure if needed in 0.11.1
#EXPOSE 22 4505:4505 4506:4506

CMD ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/supervisord.conf"]
```

Thanks,
Jason

**Comment by s0undt3ch** [comment] 2014-05-15 12:15
Yes, this is know, and right now you can't get around it.
The script needs to know that services are starting as supposed, and within docker, which only allows you to start a single process, upstarts is not running so, the services are not properly installed.

**Comment by nrgaway** [comment] 2014-05-15 13:49
I created a shell script that will allow you to install salt via bootstrap in a docker.  It just relays the install command and ignores any errors.  It will install just fine in Ubuntu and Debian using this script.

https://gist.github.com/nrgaway/277e225bac5e9a6a37b9

**Comment by darylyu** [comment] 2014-10-01 04:58
Does this problem go away with this?

http://docs.saltstack.com/en/latest/topics/releases/2014.7.0.html#next-gen-docker-management

**Comment by ross-p** [comment] 2014-11-14 02:30
No, the problem is an issue with the salt bootstrap.  It requires that `runlevel` is set, but inside a Docker container it is not.  There are some PRs to fix the issue, you can use those branches or wait for them to be merged.

**Comment by slafs** [comment] 2014-11-16 18:29
Hello! Any update on this? #455 looks nice if you ask me

**Comment by ross-p** [comment] 2014-11-17 23:28
#493 fixes the problem.

**Comment by dstokes** [comment] 2015-01-23 20:50
also

```
RUN <bootstrap_cmd>; exit 0
```

**Comment by s0undt3ch** [comment] 2015-07-17 10:49
Check services can now be skipped, pass `-d`

**Closed as completed by s0undt3ch** 2015-07-17 10:49 UTC
