### ISSUE TITLE
[BUG] Cannot install 3004 as branch was removed

### ISSUE THREAD

**Issue by realulim** [saltstack/salt-bootstrap#1926] opened 2023-05-09 11:23 UTC
**Description**
Installation of Version 3004.1 fails, because branch was removed.

```
curl -o bootstrap-salt.sh -L https://bootstrap.saltstack.com
sudo sh bootstrap-salt.sh -x python3 -P git 3004.1

```
This gives the error message:

fatal: Remote branch 3004.1 not found in upstream origin

**Setup**
Rocky Linux 8 vanilla install

Please be as specific as possible and give set-up details.

- [x] VM running on a cloud service, please be explicit and add details

**Additional context**
Please advise on how to programmatically install Salt version 3004.x

`git ls-remote --heads https://github.com/saltstack/salt.git` shows that the branch was removed. I cannot install any newer version, because they will fail on Rocky Linux 8 due to https://github.com/saltstack/salt-bootstrap/issues/1883

**Comment by whytewolf** [comment] 2023-05-09 21:18
3004.1 was never a branch. 

the issue is that a while ago someone had changed the git functionality in bootstrap to not match the documentation. and the bootstrap would automatically assume anything tried was a tagged release. and would put v in front of all references. this is not how bootstrap was ever supposed to work. you are supposed to be able to use any references. not assume everything is in the tagged refs. this was corrected recently in the bootstrap when someone pointed out they couldn't install the 3006.x branch. 

that is to say 3004.1 should be v3004.1 to match the tag which all version tags in salt have always used v<version>.

**Comment by realulim** [comment] 2023-05-10 10:36
I have tried your suggestion:

`sudo sh bootstrap-salt.sh -x python3 -P git v3004.1`

However, that didn't work either. While I did get past the error mentioned above, the installation script errored out later with this message:
```
*  INFO: Running install_rocky_linux_restart_daemons()
Job for salt-minion.service failed because the control process exited with error code.
See "systemctl status salt-minion.service" and "journalctl -xe" for details.
*  INFO: Running daemons_running()
* ERROR: salt-minion was not found running
* ERROR: Failed to run daemons_running()!!!
* ERROR: salt-minion was not found running. Pass '-D' to bootstrap-salt.sh when bootstrapping for additional debugging information...
```

**Comment by realulim** [comment] 2023-05-10 10:46
Oops, sorry, I forgot to remove EPEL, which lead to version conflicts. For the benefit of others:

You need to uninstall EPEL and also any salt-minion packages, which may have come in via EPEL instead of the bootstrap script.

**Comment by whytewolf** [comment] 2023-05-12 16:21
thank you for your update. looks like you got it solved. I"ll go ahead and close this now.

**Closed as not planned by whytewolf** 2023-05-12 16:21 UTC
Labels: Bug
