### ISSUE TITLE
Install by tag fails for v0.16 on ubuntu 12.04

### ISSUE THREAD

**Issue by jthigpen** [saltstack/salt-bootstrap#449] opened 2014-08-15 22:58 UTC
We're using this command to install salt on ubuntu 12.04

`curl -L http://bootstrap.saltstack.org | sh -s -- git v0.16.4`

The logs are super long, but the relevant section seems to be:

```
Setting up msgpack-python (0.1.10-1) ...
Setting up python-markupsafe (0.15-1) ...
Setting up python-jinja2 (2.6-1ubuntu0.1) ...
Setting up python-zmq (13.0.0-2precise) ...
Processing triggers for python-support ...
 *  INFO: Attempting to shallow clone Salt's repository from git://github.com/saltstack/salt.git
Cloning into 'salt'...
warning: Remote branch v0.16.4 not found in upstream origin, using HEAD instead
 *  INFO: Running config_salt()
 *  INFO: Running install_ubuntu_git()
2014.7.0-n/a-932aa97
running install
running build
running build_py
creating build
```

It fails to find the tag, and installs HEAD instead, which was a really weird thing to debug.

/cc @basepi @gravyboat

**Comment by s0undt3ch** [comment] 2014-08-15 23:41
Do you hsve a special need to be using such an old Salt version?

**Comment by gravyboat** [comment] 2014-08-15 23:42
@s0undt3ch @jthigpen just left, but I was speaking to him in IRC, and apparently that's just what they are still running and can't upgrade at this time.

**Comment by s0undt3ch** [comment] 2014-08-15 23:44
Just read the linked issue. Ignore my question above.

**Comment by s0undt3ch** [comment] 2014-08-15 23:45
This is a regression since we started to shallow clone Salt's repository. We'll defiantly be fixing this soon.

**Comment by s0undt3ch** [comment] 2014-08-15 23:46
Definitely

**Comment by gravyboat** [comment] 2014-08-15 23:52
@s0undt3ch Ahh that makes a lot more sense, good to know.

**Comment by s0undt3ch** [comment] 2014-08-19 03:11
Can you please try again with https://raw.github.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh

**Comment by bshelton229** [comment] 2014-08-22 17:19
@s0undt3ch bootstrapping using tags works from the development branch. Thanks!.

**Comment by s0undt3ch** [comment] 2014-08-22 19:44
On August 22, 2014 6:19:46 PM GMT+01:00, Bryan Shelton notifications@github.com wrote:

> @s0undt3ch bootstrapping using tags works from the development branch.
> Thanks!.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/saltstack/salt-bootstrap/issues/449#issuecomment-53091921

Awesome!
Pedro Algarvio @ Phone

**Comment by s0undt3ch** [comment] 2014-09-07 02:55
Closing since it's fixed.

**Closed as completed by s0undt3ch** 2014-09-07 02:55 UTC
