### ISSUE TITLE
Support Python 3.8

### ISSUE THREAD

**Issue by OrangeDog** [saltstack/salt-bootstrap#1460] opened 2020-05-11 09:34 UTC
Bootstrap has many of the same issues as the salt (use of removed and deprecated APIs), but still not fixed on master.

See also https://github.com/saltstack/salt/issues/55835

**Comment by wolfpackmars2** [comment] 2020-06-11 01:32
This should probably be tracked with the salt repo. #1444 tracks support for 20.04 in salt-bootstrap. Close as duplicate of saltstack/salt#55835 ?

**Comment by bryceml** [comment] 2020-07-14 18:29
@OrangeDog can this be closed now?

**Comment by OrangeDog** [comment] 2020-07-14 19:14
I don't know. I just created the issue after others pointed out there were still errors and deprecation warnings.

**Comment by bryceml** [comment] 2020-07-14 20:29
I'm going to assume since it now supports ubuntu 20.04 that we can say this is fixed.

**Comment by OrangeDog** [comment] 2020-07-17 11:39
The README still talks about Python 3 as if it's limited and rare, but is in fact is all that Salt now supports.

**Comment by bryceml** [comment] 2020-07-17 18:37
Sounds like we need to update the README then explaining how it decides to use python3.  I'll re-open this.

**Comment by bryceml** [comment] 2021-01-22 23:06
https://github.com/saltstack/salt-bootstrap/issues/1527 is related.

**Comment by krionbsd** [comment] 2021-09-07 10:01
Python3 is the only python version being supported right now

**Closed as completed by krionbsd** 2021-09-07 10:01 UTC
Labels: Documentation
