### ISSUE TITLE
Bootstrap fails on Ubuntu with no wget

### ISSUE THREAD

**Issue by mathrick** [saltstack/salt-bootstrap#689] opened 2015-11-07 05:00 UTC
Bootstrapping on Ubuntu 14.04 with only curl installed and no wget fails with the following:

```
install_salt.sh: 1885: install_salt.sh: wget: not found
gpg: no valid OpenPGP data found.
 * ERROR: Failed to run install_ubuntu_stable_deps()!!!
```

This is, as far as I can tell, a new issue in 2015.11.04, 2015.08.06 worked fine in this regard (although it failed in different places because of saltstack/salt#27820). The offending commit seems to be 26b82c94099f748ee42188d00096151cdbdf002f

**Comment by nasenbaer13** [comment] 2015-11-07 14:58
Duplicate of #686

**Comment by s0undt3ch** [comment] 2015-11-09 15:52
Closing since it's a duplicate

**Closed as completed by s0undt3ch** 2015-11-09 15:52 UTC
