### ISSUE TITLE
[BUG][3005][3005.0] Missing salt-archive-keyring.gpg for ubuntu 3005 or 3005.0

### ISSUE THREAD

**Issue by kevincua-umbocv** [saltstack/salt-bootstrap#1939] opened 2023-06-30 02:26 UTC
**Description**
https://repo.saltproject.io/salt/py3/ubuntu/20.04/arm64/3005/salt-archive-keyring.gpg or
https://repo.saltproject.io/salt/py3/ubuntu/20.04/arm64/minor/3005.0/salt-archive-keyring.gpg
It is also missing for ubuntu arm64 22* and 18* but not amd64 ones

**Setup**
installation process is like this
curl -o /tmp/bootstrap-salt.sh -L https://bootstrap.saltproject.io
bash /tmp/bootstrap-salt.sh -X -x python3 stable 3005.0 && rm -f /tmp/bootstrap-salt.sh
using ubuntu arm64 (ubuntu/images/hvm-ssd/ubuntu-focal-20.04-arm64-server-20210503 ami-0b616f288e67f2f4b)
using an ec2 instance

**Steps to Reproduce the behavior**
perform this on ubuntu arm64
```
curl -o /tmp/bootstrap-salt.sh -L https://bootstrap.saltproject.io
bash /tmp/bootstrap-salt.sh -X -x python3 stable 3005.0 && rm -f /tmp/bootstrap-salt.sh
```
(Include debug logs if possible and relevant)

**Expected behavior**
Until a few days or so ago, the previous command would result in a new minion, my-new-minion, running Ubuntu 20.04.

**Error Code**
 * ERROR: https://repo.saltproject.io/salt/py3/ubuntu/20.04/arm64/minor/3005.0/salt-archive-keyring.gpg failed to download to /tmp/salt-gpg-vOvQkSN4.pub

**Comment by merlinz01** [comment] 2024-04-26 00:11
Am also getting this error every time, but it doesn't seem to fail the installation:

![image](https://github.com/saltstack/salt-bootstrap/assets/158784988/1a116c1e-9a90-4f5b-afac-eb7c655e4e67)

**Comment by dmurphy18** [comment] 2024-04-26 15:49
@kevincua-umbocv There was never a 3005.0 release, at the time the first release was 3005 without a '.0', that has since subsequently changed.  Note also that 3005 is EOL and no longer supported.

The Salt 3005 release had classic and Tiamat-based packaging, but there was only support for ARM with classic packaging and for Debian 11 and Ubuntu 20.04.  Classic packaging was located at repo https://github.com/saltstack/py3, that site also had support for Python 2 under https://github.com/saltstack/yum (Redhat) & https://github.com/saltstack/apt (Debian/Ubuntu) and is no longer available.

The repo https://repo.saltproject.io/salt/py3 only has Salt 3005 Tiamat based packages.

Redhat 9 and Ubuntu 22.04 only had support via Taimat based packages in Salt 3005.

The current Salt 3006.x and 3007.x releases are based on 'onedir' architecture and packaged differently, leveraging GitHub Actions, and are fully self-contained as to dependencies, including their own Python version, currently Python 3.10.

With current releases Salt 3006.x and 3007.x, gpg keys have changed from SHA-1 previously used, to using SHA-256 keys, since SHA-1 is not supported on recent platforms due to use of OpenSSL v3.x and SHA-1 is compromised and no longer supported by later OS's (for example: Redhat 9).  Hence salt-archive-keyring.gpg is no long used for supported versions of Salt, and SALT-PROJECT-GPG-PUBKEY-2023.gpg is used instead.  @merlinz01 there is no salt-archive-keyring.gpg for latest anything.

@merlinz01 Here are the proper instructions for installing on the latest (3007.0) on Debian 11 amd64, https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/debian.html#install-salt-on-debian-11-bullseye-amd64, ARM64 support is available too, https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/debian.html#install-salt-on-debian-11-bullseye-arm64

Note: the bootstrap script is under-going large renovation and clean up at the moment to handle installs for current OS's and supported versions of Salt.

Closing since not a bug, feel free to re-open or if you have any other questions.

**Closed as completed by dmurphy18** 2024-04-26 15:49 UTC
Labels: Expected Behavior, Packaging
