### ISSUE TITLE
Non-Development Script Broken on Amazon Linux

### ISSUE THREAD

**Issue by dennisfoconnor** [saltstack/salt-bootstrap#742] opened 2016-01-25 16:25 UTC
When using the stable script on amazon linux this happend:

```
 *  INFO: sh install_salt.sh -- Version 2015.11.09

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   4.1.10-17.31.amzn1.x86_64
 *  INFO:   Distribution: Amazon Linux AMI 2015.09

 *  INFO: Installing minion
 *  INFO: Found function install_amazon_linux_ami_deps
 *  INFO: Found function install_amazon_linux_ami_stable
 *  INFO: Found function install_amazon_linux_ami_stable_post
 *  INFO: Found function install_amazon_linux_ami_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Running install_amazon_linux_ami_deps()
warning: /var/tmp/rpm-tmp.E9i9YT: Header V3 RSA/SHA256 Signature, key ID 0608b895: NOKEY
Retrieving http://mirrors.kernel.org/fedora-epel/6/x86_64/epel-release-6-8.noarch.rpm
Preparing...                          ########################################
Updating / installing...
epel-release-6-8                      ########################################
Cleaning up / removing...
epel-release-6-8.9.amzn1              ########################################
 *  INFO: Adding SaltStack's COPR repository
Loaded plugins: priorities, update-motd, upgrade-helper
File contains no section headers.
file: file:///etc/yum.repos.d/saltstack-salt-epel-6.repo, line: 1
'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n'
Usage: yum [options] COMMAND

List of Commands:

autoremove     Remove leaf packages
check          Check for problems in the rpmdb
check-update   Check for available package updates
clean          Remove cached data
deplist        List a package's dependencies
distribution-synchronization Synchronize installed packages to the latest available versions
downgrade      downgrade a package
erase          Remove a package or packages from your system
fs             Creates filesystem snapshots, or lists/deletes current snapshots.
fssnapshot     Creates filesystem snapshots, or lists/deletes current snapshots.
groups         Display, or use, the groups information
help           Display a helpful usage message
history        Display, or use, the transaction history
info           Display details about a package or group of packages
install        Install a package or packages on your system
list           List a package or groups of packages
load-transaction load a saved transaction from filename
makecache      Generate the metadata cache
provides       Find what package provides the given value
reinstall      reinstall a package
repo-pkgs      Treat a repo. as a group of packages, so we can install/remove all of them
repolist       Display the configured software repositories
search         Search package details for the given string
shell          Run an interactive yum shell
swap           Simple way to swap packages, instead of using shell
update         Update a package or packages on your system
update-minimal Works like upgrade, but goes to the 'newest' package match which fixes a problem that affects your system
updateinfo     Acts on repository update information
upgrade        Update packages taking obsoletes into account
version        Display a version for the machine and/or available repos.


Options:
  -h, --help            show this help message and exit
  -t, --tolerant        be tolerant of errors
  -C, --cacheonly       run entirely from system cache, don't update cache
  -c [config file], --config=[config file]
                        config file location
  -R [minutes], --randomwait=[minutes]
                        maximum command wait time
  -d [debug level], --debuglevel=[debug level]
                        debugging output level
  --showduplicates      show duplicates, in repos, in list/search commands
  -e [error level], --errorlevel=[error level]
                        error output level
  --rpmverbosity=[debug level name]
                        debugging output level for rpm
  -q, --quiet           quiet operation
  -v, --verbose         verbose operation
  -y, --assumeyes       answer yes for all questions
  --assumeno            answer no for all questions
  --version             show Yum version and exit
  --installroot=[path]  set install root
  --enablerepo=[repo]   enable one or more repositories (wildcards allowed)
  --disablerepo=[repo]  disable one or more repositories (wildcards allowed)
  -x [package], --exclude=[package]
                        exclude package(s) by name or glob
  --disableexcludes=[repo]
                        disable exclude from main, for a repo or for
                        everything
  --disableincludes=[repo]
                        disable includepkgs for a repo or for everything
  --obsoletes           enable obsoletes processing during updates
  --noplugins           disable Yum plugins
  --nogpgcheck          disable gpg signature checking
  --disableplugin=[plugin]
                        disable plugins by name
  --enableplugin=[plugin]
                        enable plugins by name
  --skip-broken         skip packages with depsolving problems
  --color=COLOR         control whether color is used
  --releasever=RELEASEVER
                        set value of $releasever in yum config and repo files
  --downloadonly        don't update, just download
  --downloaddir=DLDIR   specifies an alternate directory to store packages
  --setopt=SETOPTS      set arbitrary config and repo options
  --bugfix              Include bugfix relevant packages, in updates
  --security            Include security relevant packages, in updates
  --advisory=ADVS, --advisories=ADVS
                        Include packages needed to fix the given advisory, in
                        updates
  --bzs=BZS             Include packages needed to fix the given BZ, in
                        updates
  --cves=CVES           Include packages needed to fix the given CVE, in
                        updates
  --sec-severity=SEVS, --secseverity=SEVS
                        Include security relevant packages matching the
                        severity, in updates

  Plugin Options:
    --samearch-priorities
                        Priority-exclude packages based on name + arch
 * ERROR: Failed to run install_amazon_linux_ami_deps()!!!
```

The installation works fine using the develop script.

The issue appears to be with the /etc/yum.repos.d/saltstack-salt-epel-6.repo file.

**Comment by federicobaldo** [comment] 2016-01-25 16:45
I suppose this is related to https://github.com/saltstack/salt-bootstrap/commit/f8715cb97fe18349567ef03bf37c130e53a27b49 Any chance that commit can be moved to the stable script?

**Comment by tskinn** [comment] 2016-01-25 16:47
I can confirm this issue. The exact same thing is happening in our systems.

**Comment by scsinutz** [comment] 2016-01-25 17:55
Confirmed as well. This is breaking our automation.

cat /etc/yum.repos.d/saltstack-salt-epel-6.repo

``` HTML
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://copr.fedorainfracloud.org/coprs/saltstack/salt/repo/epel-6/saltstack-salt-epel-6.repo">here</a>.</p>
<hr>
<address>Apache/2.4.6 (Red Hat Enterprise Linux) Server at copr.fedoraproject.org Port 80</address></body></html>
```

**Comment by jfindlay** [comment] 2016-01-25 21:16
Thanks for the info.  I will be working on a new stable bootstrap version this week.

**Comment by jfindlay** [comment] 2016-01-25 21:17
Until then you can work around this by running `salt-cloud --update-bootstrap` or similar.

**Comment by danielgblanco** [comment] 2016-01-26 12:13
I've just done a  `salt-cloud --update-bootstrap` but I still have version `2015.11.09` with the old COPR URL's...

**Comment by mlalpho** [comment] 2016-01-26 14:42
fixed by #738 ?

**Comment by mlalpho** [comment] 2016-01-26 14:47
@danielgblanco You can also manually maintain the file `/etc/salt/cloud.deploy.d/bootstrap-salt.sh` on your salt-cloud machine.  :+1:

**Comment by danielgblanco** [comment] 2016-01-26 14:53
Will that not get overwritten at some point?

**Comment by mlalpho** [comment] 2016-01-26 14:54
only if you were to use salt-cloud cli to force the update.. which should prompt you before it overwrites

**Comment by danielgblanco** [comment] 2016-01-26 16:03
Thanks :+1: just did that and everything's working again.

**Comment by scsinutz** [comment] 2016-01-28 18:27
How to get around this issue with Packer? The Packer salt provisioner calls "curl -L https://bootstrap.saltstack.com" to get salt installed.

**Comment by dearing** [comment] 2016-01-30 23:34
> How to get around this issue with Packer? The Packer salt provisioner calls "curl -L https://bootstrap.saltstack.com" to get salt installed.

provision.sh

``` shell
curl -L https://raw.githubusercontent.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh | sudo sh -s -- -FU

```

``` json
{
  "type": "salt-masterless",
  "skip_bootstrap": true,
  "local_state_tree": "./provisioners/salt-masterless/salt/"
}
```
- https://www.packer.io/docs/provisioners/salt-masterless.html#skip_bootstrap

**Comment by scsinutz** [comment] 2016-02-01 20:30
dearing, That fixed it! Thank you!

**Comment by pschipitsch** [comment] 2016-02-03 22:24
This is breaking our Packer builds using salt-masterless.

**Comment by scsinutz** [comment] 2016-02-03 22:27
pschipitsch, I had the same problem but dearing comment fixed it for me. 

give it a try...

**Comment by vutny** [comment] 2016-02-04 12:18
@dennisfoconnor `stable` branch of `salt-bootstrap` is outdated. Better to use `develop` for now.
I'm looking forward for all recent changes to be merged into `stable`.
https://bootstrap.saltstack.com redirects to http://bootstrap.saltstack.com/stable/bootstrap-salt.sh. You can use https://bootstrap.saltstack.com/develop.

Also, we still need #691 to be resolved.

**Comment by kshenk1** [comment] 2016-02-05 20:40
Maybe I'm not understanding. I thought we could use the `develop` version?

I pulled https://raw.githubusercontent.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh to `/etc/salt/cloud.deploy.d/bootstrap-salt.sh`, and salt-cloud still fails for me

```
 * ERROR: Failed to run install_centos_git_deps()!!!
Error: There was a profile error: Command 'ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oKbdInteractiveAuthentication=no -i keyfile.pem -p 22 root@1.2.3.4 \'/tmp/.saltcloud-b5f13ee0-98c6-4bb2-b961-c5435152dc0f/deploy.sh -c \'"\'"\'/tmp/.saltcloud-b5f13ee0-98c6-4bb2-b961-c5435152dc0f\'"\'"\' -H http://proxy.svcs:3128 -G -Z git v2015.5.1\'' failed. Exit code: 1
```

**Comment by mlalpho** [comment] 2016-02-06 15:51
This started showing up from EPEL recently:
```
 *  INFO: Running install_centos_stable_deps()
http://mirror.cc.columbia.edu/pub/linux/epel/7/x86_64/repodata/7647c6fa236e97377fb75e7f30dd00c02594f56520425bc7281dc112203c4696-primary.sqlite.xz: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below knowledge base article

https://access.redhat.com/articles/1320623

If above article doesn't help to resolve this issue please create a bug on https://bugs.centos.org/
```

**Comment by mlalpho** [comment] 2016-02-06 15:52
A run of `./deploy.sh` from the failed minion is a success. Perhaps a retcode issue there??

**Comment by mlalpho** [comment] 2016-02-06 15:55
```shell
[ec2-user ~]$ cd /etc/yum.repos.d/
[ec2-user yum.repos.d]$ ls
CentOS-Base.repo       CentOS-fasttrack.repo  CentOS-Vault.repo  repo-saltstack-el7.repo
CentOS-CR.repo         CentOS-Media.repo      epel.repo
CentOS-Debuginfo.repo  CentOS-Sources.repo    epel-testing.repo
[ec2-user yum.repos.d]$ cat epel.repo
[epel]
name=Extra Packages for Enterprise Linux 7 - $basearch
#baseurl=http://download.fedoraproject.org/pub/epel/7/$basearch
mirrorlist=https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
failovermethod=priority
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7

[epel-debuginfo]
name=Extra Packages for Enterprise Linux 7 - $basearch - Debug
#baseurl=http://download.fedoraproject.org/pub/epel/7/$basearch/debug
mirrorlist=https://mirrors.fedoraproject.org/metalink?repo=epel-debug-7&arch=$basearch
failovermethod=priority
enabled=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
gpgcheck=1

[epel-source]
name=Extra Packages for Enterprise Linux 7 - $basearch - Source
#baseurl=http://download.fedoraproject.org/pub/epel/7/SRPMS
mirrorlist=https://mirrors.fedoraproject.org/metalink?repo=epel-source-7&arch=$basearch
failovermethod=priority
enabled=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
gpgcheck=1
```

**Comment by mlalpho** [comment] 2016-02-06 17:13
@kshenk1 I'm not sure if your issue is related. 

I tried to run your install with script args: -G -Z git v2015.5.1  on a Centos6 image

I ended up getting a bunch of python lib conflicts:

```
Dependencies Resolved

================================================================================
 Package                   Arch   Version              Repository          Size
================================================================================
Installing:
 m2crypto                  x86_64 0.20.2-9.el6         base               471 k
 python-crypto             x86_64 2.6.1-2.el6          repo-saltstack-el6 501 k
 python-jinja2             x86_64 2.2.1-2.el6_5        base               466 k
 python-msgpack            x86_64 0.4.6-1.el6          repo-saltstack-el6  68 k
 python-requests           noarch 2.6.0-3.el6          base                95 k
 python-zmq                x86_64 14.5.0-2.el6         repo-saltstack-el6 479 k
Updating:
 PyYAML                    x86_64 3.11-1.el6           repo-saltstack-el6 152 k
 chkconfig                 x86_64 1.3.49.3-5.el6       base               159 k
 yum-utils                 noarch 1.1.30-30.el6        base               110 k
Installing for dependencies:
 make                      x86_64 1:3.81-20.el6        base               389 k
 python-babel              noarch 0.9.4-5.1.el6        base               1.4 M
 python-backports          x86_64 1.0-5.el6            base               5.5 k
 python-backports-ssl_match_hostname
                           noarch 3.4.0.2-4.el6.centos extras              13 k
 python-chardet            noarch 2.2.1-1.el6          base               230 k
 python-six                noarch 1.9.0-2.el6          base                28 k
 python-urllib3            noarch 1.10.2-1.el6         base               101 k
 zeromq                    x86_64 4.0.5-4.el6          repo-saltstack-el6 568 k
Updating for dependencies:
 ntsysv                    x86_64 1.3.49.3-5.el6       base                29 k
 openssl                   x86_64 1.0.1e-42.el6_7.2    updates            1.5 M
 python-libs               x86_64 2.6.6-64.el6         base               5.3 M
 yum                       noarch 3.2.29-69.el6.centos base               1.0 M
 zlib                      x86_64 1.2.3-29.el6         base                73 k

Transaction Summary
================================================================================
Install      14 Package(s)
Upgrade       8 Package(s)

Total download size: 13 M
Downloading Packages:
--------------------------------------------------------------------------------
Total                                           1.8 MB/s |  13 MB     00:07
warning: rpmts_HdrFromFdno: Header V4 RSA/SHA1 Signature, key ID de57bfbe: NOKEY
Retrieving key from https://repo.saltstack.com/yum/rhel6/SALTSTACK-GPG-KEY.pub
Importing GPG key 0xDE57BFBE:
 Userid: "SaltStack Packaging Team <packaging@saltstack.com>"
 From  : https://repo.saltstack.com/yum/rhel6/SALTSTACK-GPG-KEY.pub
Running rpm_check_debug
Running Transaction Test


Transaction Check Error:
  file /usr/lib64/python2.6/ctypes/__init__.py from install of python-libs-2.6.6-64.el6.x86_64 conflicts with file from package python-2.6.6-29.el6_3.3.x86_64
  file /usr/lib64/python2.6/logging/__init__.py from install of python-libs-2.6.6-64.el6.x86_64 conflicts with file from package python-2.6.6-29.el6_3.3.x86_64
  file /usr/lib64/python2.6/bsddb/__init__.pyc from install of python-libs-2.6.6-64.el6.x86_64 conflicts with file from package python-2.6.6-29.el6_3.3.x86_64
  file /usr/lib64/python2.6/compiler/__init__.pyc from install of python-libs-2.6.6-64.el6.x86_64 conflicts with file from package python-2.6.6-29.el6_3.3.x86_64
  file /usr/lib64/python2.6/ctypes/__init__.pyc from install of python-libs-2.6.6-64.el6.x86_64 conflicts with file from package python-2.6.6-29.el6_3.3.x86_64
  file /usr/lib64/python2.6/ctypes/macholib/__init__.pyc from install of python-libs-2.6.6-64.el6.x86_64 conflicts with file from package python-2.6.6-29.el6_3.3.x86_64
  file /usr/lib64/python2.6/curses/__init__.pyc from install of python-libs-2.6.6-64.el6.x86_64 conflicts with file from package python-2.6.6-29.el6_3.3.x86_64
  file /usr/lib64/python2.6/distutils/__init__.pyc from install of python-libs-2.6.6-64.el6.x86_64 conflicts with file from package python-2.6.6-29.el6_3.3.x86_64
  file /usr/lib64/python2.6/distutils/command/__init__.pyc from install of python-libs-2.6.6-64.el6.x86_64 conflicts with file from package python-2.6.6-29.el6_3.3.x86_64
  file /usr/lib64/python2.6/email/__init__.pyc from install of python-libs-2.6.6-64.el6.x86_64 conflicts with file from package python-2.6.6-29.el6_3.3.x86_64
  file /usr/lib64/python2.6/email/mime/__init__.pyc from install of python-libs-2.6.6-64.el6.x86_64 conflicts with file from package python-2.6.6-29.el6_3.3.x86_64
  file /usr/lib64/python2.6/encodings/__init__.pyc from install of python-libs-2.6.6-64.el6.x86_64 conflicts with file from package python-2.6.6-29.el6_3.3.x86_64
  file /usr/
```

If I change the script_args to `-U -G -Z git v2015.5.1`, so that yum updates before anything.. It works! :+1:

Let me know if that helps at all .. Cheers! :beers:

**Comment by kshenk1** [comment] 2016-02-07 04:01
Soooo... I'm almost embarrassed to say that this turned out to be my proxy, which I just didn't think about because the particular instance I was provisioning has a public interface, but proxy's all provisioning. A proxy for the interactive shell wasn't yet in place on the instance - so when I'd ssh in I could pull the saltstack repo key just fine, however; the bootstrap script couldn't seem to get it. Then, it dawned on me that this was a new domain that I hadn't added to the proxy acls yet :-\

**Comment by jfindlay** [comment] 2016-04-14 22:56
Since this is fixed with the develop version of the script, which will be released in a few days, I'm going to close this issue.  If anyone is still finding problems with the develop version, please comment here with the details and I'll reopen it.

**Comment by rallytime** [comment] 2016-07-05 23:44
A couple of releases have now come out on the stable branch. Per @jfindlay's comment above, I am going to close this. For reference, the latest stable release is `2016.06.27`.

**Closed as completed by rallytime** 2016-07-05 23:44 UTC
Labels: Bug
