### ISSUE TITLE
Vagrant Salt plugin now fails with updates to bootstrap

### ISSUE THREAD

**Issue by howardroark** [saltstack/salt-bootstrap#285] opened 2014-01-25 23:30 UTC
The salt plugin attempts to run this as root:

```
/tmp/bootstrap_salt.sh  -c /tmp
```

Which contains this:

```
#!/bin/sh -

# We just download the bootstrap script by default and execute that.
if [ -x /usr/bin/fetch ]; then
    /usr/bin/fetch -o - http://bootstrap.saltstack.org | sh -s -- "$@"
elif [ -x /usr/bin/curl ]; then
    /usr/bin/curl -L http://bootstrap.saltstack.org | sh -s -- "$@"
else
    python \
        -c 'import urllib; print urllib.urlopen("http://bootstrap.saltstack.org").read()' \
        | sh -s -- "$@"
fi
```

I can see that it is the "-c /tmp" argument that makes it fail.

Here is the error that occurs:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   256  100   256    0     0     12      0  0:00:21  0:00:20  0:00:01  8533
sh: 206: __check_config_dir: not found
 * ERROR: The configuration directory  does not exist.
```

This occurs on Debian 7 and Ubuntu 12.04

Appreciate any thoughts!

**Comment by howardroark** [comment] 2014-01-25 23:58
Edited my original comment...

**Comment by phs** [comment] 2014-01-26 00:30
The fix appears to be committed, but the bug still reproduces due to https://raw.github.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh not being updated yet (unless perhaps I have some local caching?)  When can we expect that to happen?

**Comment by ajw0100** [comment] 2014-01-26 01:27
Doesn't look like caching. Looks like we're just waiting for 5340e62461aa3bb7e391591eb8356c798b808956 to be merged into stable.

**Comment by howardroark** [comment] 2014-01-26 01:53
@s0undt3ch  ...Because of the way this affects the vagrant salt integration it would be very helpful to have your fix in 1.5.11 released right away.  The issue sort of jams up the vagrant boot process, and in a lot of cases the tools are being used in teams where not everyone will have the proper knowledge to diagnose. 

Thanks if you can help with this in any way!

**Comment by ajw0100** [comment] 2014-01-26 02:30
This is also causing salt-cloud deployments to fail:

`Executing the command '/tmp/.saltcloud/deploy.sh -c /tmp/.saltcloud' failed`

**Comment by mbj** [comment] 2014-01-26 15:45
I use the following workaround in my vagrant setup:

``` ruby
  # Install system dependencies with salt
  config.vm.provision :salt do |salt|
    salt.minion_config = 'salt/minion'
    salt.bootstrap_script = File.expand_path('../bootstrap-salt.sh', __FILE__)
    salt.run_highstate = true
  end
```

My `bootstrap-salt.sh` file has the following contents:

```
#!/bin/sh -

# We nail salt 1.5.9 because bootstrap for latest stable, 1.5.10, is broken.
# 
# Once this commit was released we can use the stable version again:
#
# https://github.com/saltstack/salt-bootstrap/commit/5340e62461aa3bb7e391591eb8356c798b808956

python \
    -c 'import urllib; print urllib.urlopen("https://raw.github.com/saltstack/salt-bootstrap/09b7d59450708e0cb6338dbe4c49a42c01b1188e/bootstrap-salt.sh").read()' \
    | sh -s -- "$@"
```

I hope this helps others till stable was fixed. The URL I hardcoded references `bootstrap-salt.sh` at tag `1.5.9`.

**Comment by s0undt3ch** [comment] 2014-01-26 17:57
I've just released v1.5.11 hopefully solves everyone's problems.

Sorry for the breakage.

Please re-open if this is still a problem.

**Closed as completed by s0undt3ch** 2014-01-26 17:57 UTC

**Comment by howardroark** [comment] 2014-01-26 18:10
All is well!

Thanks for this!

**Comment by s0undt3ch** [comment] 2014-01-26 18:44
Anytime! Just wished I had seen the left behind commit initially...
