### ISSUE TITLE
Missing salt files for 20.10

### ISSUE THREAD

**Issue by povils** [saltstack/salt-bootstrap#1512] opened 2020-12-04 12:04 UTC
I am trying to install salt on Ubuntu 20.10 and it fails on getting packages from: http://repo.saltstack.com/py3/ubuntu/
Is this intented? If yes what is workaround?

**Comment by jpacura** [comment] 2020-12-05 21:43
Saltstack doesn't have repos for non-LTS versions of Ubuntu. They only promise best-effort support for non-LTS versions. The script will correctly detect 18.10, 19.04, and 19.10 as 18.04, but there is no code for detecting 20.10 as 20.04. I have confirmed that the 20.04 packages will install on a 20.10 docker container. This is very similar to [the PR I have open for Debian 11 support](https://github.com/saltstack/salt-bootstrap/issues/1513), so I wouldn't mind fixing this too.

**Comment by jpacura** [comment] 2021-01-22 23:24
Unless there are any objections, I will remove support for Ubuntu 17.04, 17.10, and 18.10, since they are not LTS releases, and are all end-of-life. 

The readme specifies the following:

> Non-LTS Ubuntu releases are not supported once the release reaches End-of-Life as defined by Ubuntu's release schedule.

**Comment by jpacura** [comment] 2021-01-22 23:38
I'll also remove support for 14.04, because the saltstack repos seem to have been removed, so the script fails

**Comment by jpacura** [comment] 2021-01-23 00:00
Opened https://github.com/saltstack/salt-bootstrap/issues/1528 to track the removal of EOL versions of Ubuntu and Debian

**Comment by bryceml** [comment] 2021-01-25 18:07
Closing since the PR got merged.

**Closed as completed by bryceml** 2021-01-25 18:07 UTC
