### ISSUE TITLE
salt-bootstrap broken against SLES 11

### ISSUE THREAD

**Issue by ixela** [saltstack/salt-bootstrap#101] opened 2013-03-28 14:26 UTC
At one point this was working, as I have a submitted copy that installs just fine. However, I can no longer install salt using the bootstrap script. 

This is the output of the script:

```
*  INFO: /bin/sh /apps/bootstrap-salt.sh -- Version 1.5.2
 *  WARN: Running the unstable version of bootstrap-salt.sh

 *  INFO: System Information:
 *  INFO:   CPU:          AuthenticAMD
:
AuthenticAMD
:
AuthenticAMD
:
AuthenticAMD
:
AuthenticAMD
:
AuthenticAMD
:
AuthenticAMD
:
AuthenticAMD
:
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   2.6.32.59-0.7-default
 *  INFO:   Distribution: SUSE LINUX 11

 *  INFO: Installing minion
DISTRONAME: SUSE LINUX

 *  INFO: Found function daemons_running
 * ERROR: No dependencies installation function found. Exiting...
```

This is on both SLES 11 SP 1 and SLES 11 SP 2. 

This appears to be a regression from the previous versions.

**Comment by s0undt3ch** [comment] 2013-03-28 14:34
@ixela if you download the script and revert the changes done in https://github.com/saltstack/salt-bootstrap/commit/15ba544c7f6d4d64a7e26ffcbf4bc0671b627e85 do you still verify the same problem?

**Comment by ixela** [comment] 2013-03-28 15:54
Here is the output if I revert the changes to CPU_VENDOR_ID. None of the
other changes modified output.
-  INFO: /bin/sh /apps/bootstrap-salt.sh -- Version 1.5.2
  -  WARN: Running the unstable version of bootstrap-salt.sh
  -  INFO: System Information:
  -  INFO:   CPU:          AuthenticAMD
  -  INFO:   CPU Arch:     x86_64
  -  INFO:   OS Name:      Linux
  -  INFO:   OS Version:   2.6.32.59-0.7-default
  -  INFO:   Distribution: SUSE LINUX 11
  -  INFO: Installing minion
    DISTRONAME: SUSE LINUX
  -  INFO: Found function daemons_running
  - ERROR: No dependencies installation function found. Exiting...

**Comment by ixela** [comment] 2013-03-28 15:56
-  INFO: /bin/sh /apps/bootstrap-salt.sh -- Version 1.5.2
  -  WARN: Running the unstable version of bootstrap-salt.sh
  -  INFO: System Information:
  -  INFO:   CPU:          AuthenticAMD
  -  INFO:   CPU Arch:     x86_64
  -  INFO:   OS Name:      Linux
  -  INFO:   OS Version:   2.6.32.59-0.7-default
  -  INFO:   Distribution: SUSE LINUX 11
  -  INFO: Installing minion
  -  INFO: Found function daemons_running
  - ERROR: No dependencies installation function found. Exiting...

Is a more correct version. I had a debug echo inserted on the previous
paste.

On Thu, Mar 28, 2013 at 10:54 AM, matthew willson <matthewkwillson@gmail.com

> wrote:
> 
> Here is the output if I revert the changes to CPU_VENDOR_ID. None of the
> other changes modified output.
> -  INFO: /bin/sh /apps/bootstrap-salt.sh -- Version 1.5.2
>   -  WARN: Running the unstable version of bootstrap-salt.sh
>   -  INFO: System Information:
>   -  INFO:   CPU:          AuthenticAMD
>   -  INFO:   CPU Arch:     x86_64
>   -  INFO:   OS Name:      Linux
>   -  INFO:   OS Version:   2.6.32.59-0.7-default
>   -  INFO:   Distribution: SUSE LINUX 11
>   -  INFO: Installing minion
>     DISTRONAME: SUSE LINUX
>   -  INFO: Found function daemons_running
>   - ERROR: No dependencies installation function found. Exiting...
>

**Comment by s0undt3ch** [comment] 2013-03-28 22:15
Heh, I forgot to ask for your to use `-D` for extra debug output. Could you?

**Comment by s0undt3ch** [comment] 2013-04-10 18:26
Do you still see this issue in latest stable?

```
curl -L http://bootstrap.saltstack.org | sudo sh -s -- -D
```

**Comment by ixela** [comment] 2013-04-10 18:38
I haven't tested since every time I go to update salt something kills
integration with SLES. I got tired of attempting to back engineer solutions
so I haven't spent much time on it. I'll look into it in the next week.

**Comment by aboe76** [comment] 2013-04-12 15:17
@ixela, if there are problems with how salt installs itself on Suse and/or Opensuse please let me know.
I maintain the packages on build.opensuse.org in the python repo..

**Comment by ixela** [comment] 2013-04-12 16:16
We currently use SLES 11 SP 1 in production, which isn't an enabled build
target for the python repo listed in build.opensuse.org. Also, the boot
strap script still doesn't work. I've fixed it previously, but various
rewrites of the boot strap script have broken it again. Here is the output
of curl -L http://bootstrap.saltstack.org | sudo sh -s -- -D
-  INFO: PIPED THROUGH sh -- Version 1.5.3
  #!/bin/sh -
  -  INFO: System Information:
  -  INFO:   CPU:          AuthenticAMD
    :
    AuthenticAMD
    :
    AuthenticAMD
    :
    AuthenticAMD
    :
    AuthenticAMD
    :
    AuthenticAMD
    :
    AuthenticAMD
    :
    AuthenticAMD
    :
-  INFO:   CPU Arch:     x86_64
-  INFO:   OS Name:      Linux
-  INFO:   OS Version:   2.6.32.59-0.7-default
-  INFO:   Distribution: SUSE LINUX 11
  -  INFO: Installing minion
  - DEBUG: install_suse_linux_11_stable_deps not found....
  - DEBUG: install_suse_linux_11_deps not found....
  - DEBUG: install_suse_linux_stable_deps not found....
  - DEBUG: install_suse_linux_deps not found....
  - DEBUG: install_suse_linux_11_stable not found....
  - DEBUG: install_suse_linux_stable not found....
  - DEBUG: install_suse_linux_11_stable_post not found....
  - DEBUG: install_suse_linux_11_post not found....
  - DEBUG: install_suse_linux_stable_post not found....
  - DEBUG: install_suse_linux_post not found....
  - DEBUG: install_suse_linux_11_stable_restart_daemons not found....
  - DEBUG: install_suse_linux_11_restart_daemons not found....
  - DEBUG: install_suse_linux_stable_restart_daemons not found....
  - DEBUG: install_suse_linux_restart_daemons not found....
  - DEBUG: daemons_running_suse_linux_11_stable not found....
  - DEBUG: daemons_running_suse_linux_11 not found....
  - DEBUG: daemons_running_suse_linux_stable not found....
  - DEBUG: daemons_running_suse_linux not found....
  -  INFO: Found function daemons_running
  - ERROR: No dependencies installation function found. Exiting...
  - DEBUG: Removing the logging pipe /tmp/bootstrap-salt.logpipe
  - DEBUG: Killing logging pipe tee's with pid(s): 29886

To remove the issue with the multiple AuthenticAMD outputs, revert changes
made to line 350 in the salt-bootstrap script. It was not tested against
non-intel chips and doesn't work correctly. The functions that it attempts
to find called suse_linux_11 don't exist. However, the functions I wrote
called suse_11 do exist. This appears to be a naming convention issue that
was overlooked at some point, since those functions previously worked.
This is the previous way to determine CPU type without printing one line
for each core:

grep -E 'vendor_id|Processor' /proc/cpuinfo | head -n 1 | awk '{print $3}'
| cut -d '-' -f1

The changes I made to fix the init files in the bootstrap script have also
been removed, so none of the init files work out of the gate. I've
previously submitted sed statements that will correct the default paths to
the ones that actually exist after installation from either pip or git.
This holds true for both SP1 and SP2 from my own testing. I've attempted to
previously submit patches against the init scripts themselves but they were
not accepted so I created the sed lines instead. Here is the sed line to
fix the salt-minion init.d script:

sed
's/SALTMINION=\/usr\/bin\/salt-minion/SALTMINION=\/usr\/local\/bin\/salt-minion/g'

Also, the chkconfig lines for the suse_11 functions are missing again.

Regarding the opensuse build for python, I'm not entirely sure how to use
that on SLES 11 SP 1. I try to avoid installing non-suse provided packages
through zypper. I've primarily installed salt through pip or git, though I
avoid pip since I can't specify a version which leads to a lot of issues.

**Comment by aboe76** [comment] 2013-04-12 16:19
try my personal repo: these rpms you can put in your Suse Subscription Management server.
(smt custom repo)

https://build.opensuse.org/project/show?project=home%3Aaboe76

**Comment by s0undt3ch** [comment] 2013-04-12 17:36
@aboe76 Thanks for pitching in...

On 12-04-2013 17:16, Matthew Willson wrote:

> We currently use SLES 11 SP 1 in production, which isn't an enabled build
> target for the python repo listed in build.opensuse.org. Also, the boot
> strap script still doesn't work. I've fixed it previously, but various
> rewrites of the boot strap script have broken it again. Here is the
> output
> of curl -L http://bootstrap.saltstack.org | sudo sh -s -- -D
> - INFO: PIPED THROUGH sh -- Version 1.5.3
>   #!/bin/sh -
> - INFO: System Information:
> - INFO: CPU: AuthenticAMD
>   :
>   AuthenticAMD
>   :
>   AuthenticAMD
>   :
>   AuthenticAMD
>   :
>   AuthenticAMD
>   :
>   AuthenticAMD
>   :
>   AuthenticAMD
>   :
>   AuthenticAMD
>   :
> - INFO: CPU Arch: x86_64
> - INFO: OS Name: Linux
> - INFO: OS Version: 2.6.32.59-0.7-default
> - INFO: Distribution: SUSE LINUX 11
> - INFO: Installing minion
> - DEBUG: install_suse_linux_11_stable_deps not found....
> - DEBUG: install_suse_linux_11_deps not found....
> - DEBUG: install_suse_linux_stable_deps not found....
> - DEBUG: install_suse_linux_deps not found....
> - DEBUG: install_suse_linux_11_stable not found....
> - DEBUG: install_suse_linux_stable not found....
> - DEBUG: install_suse_linux_11_stable_post not found....
> - DEBUG: install_suse_linux_11_post not found....
> - DEBUG: install_suse_linux_stable_post not found....
> - DEBUG: install_suse_linux_post not found....
> - DEBUG: install_suse_linux_11_stable_restart_daemons not found....
> - DEBUG: install_suse_linux_11_restart_daemons not found....
> - DEBUG: install_suse_linux_stable_restart_daemons not found....
> - DEBUG: install_suse_linux_restart_daemons not found....
> - DEBUG: daemons_running_suse_linux_11_stable not found....
> - DEBUG: daemons_running_suse_linux_11 not found....
> - DEBUG: daemons_running_suse_linux_stable not found....
> - DEBUG: daemons_running_suse_linux not found....
> - INFO: Found function daemons_running
> - ERROR: No dependencies installation function found. Exiting...
> - DEBUG: Removing the logging pipe /tmp/bootstrap-salt.logpipe
> - DEBUG: Killing logging pipe tee's with pid(s): 29886
> 
> To remove the issue with the multiple AuthenticAMD outputs, revert
> changes
> made to line 350 in the salt-bootstrap script. It was not tested against
> non-intel chips and doesn't work correctly. The functions that it
> attempts
> to find called suse_linux_11 don't exist. However, the functions I wrote
> called suse_11 do exist. This appears to be a naming convention issue
> that
> was overlooked at some point, since those functions previously worked.
> This is the previous way to determine CPU type without printing one line
> for each core:
> 
> grep -E 'vendor_id|Processor' /proc/cpuinfo | head -n 1 | awk '{print
> $3}'
> | cut -d '-' -f1

@ixela  The multiple `AuthenticAMD` issue is fixed in my own repo. I'll
get it into salt-bootstrap soon.

I also need the output and contents of all files matching
`/etc/*release` and also the output of `lsb_release -si` if available.
Of course, if no sensitive data is involved.

So far, all the SuSE amazon AMI's I've tested against are properly
identified as SuSE and not SuSE Linux, yes, ignoring "linux" is a naming
convention, yours are being identified as SuSE Linux, hence me asking
for additional information.

> The changes I made to fix the init files in the bootstrap script have
> also
> been removed, so none of the init files work out of the gate. I've
> previously submitted sed statements that will correct the default
> paths to
> the ones that actually exist after installation from either pip or git.
> This holds true for both SP1 and SP2 from my own testing. I've
> attempted to
> previously submit patches against the init scripts themselves but they
> were
> not accepted so I created the sed lines instead. Here is the sed line to
> fix the salt-minion init.d script:
> 
> sed
> 's/SALTMINION=\/usr\/bin\/salt-minion/SALTMINION=\/usr\/local\/bin\/salt-minion/g'
> 
> Also, the chkconfig lines for the suse_11 functions are missing again.

Some of your changes to the SuSE support were either removed or reverted
back because they were proven not to be good enough at that
time(although I did accept them). We've made quite an effort to support
SuSE 11 SP1, but if specific things are still missing or failing, we're
happy to fix them(we just need to be able to reproduce the issue).

> Regarding the opensuse build for python, I'm not entirely sure how to use
> that on SLES 11 SP 1. I try to avoid installing non-suse provided
> packages
> through zypper. I've primarily installed salt through pip or git,
> though I
> avoid pip since I can't specify a version which leads to a lot of issues.

Sure you can specify a version!

```
$ pip install salt==0.12.0
Downloading/unpacking salt==0.12.0
  Downloading salt-0.12.0.tar.gz (943kB): 943kB downloaded
  Storing download in cache at
./.pip/cache/http%3A%2F%2Fpypi.python.org%2Fpackages%2Fsource%2Fs%2Fsalt%2Fsalt-0.12.0.tar.gz
```

**Comment by ixela** [comment] 2013-04-12 17:50
Ah, I didn't know I could do that with pip. That makes things a bit easier.

We have three files with the *-release name scheme.
ASC-release:
Thu Dec 22 13:58:27 CST 2011
lsb-release:
LSB_VERSION="core-2.0-noarch:core-3.2-noarch:core-4.0-noarch:core-2.0-x86_64:core-3.2-x86_64:core-4.0-x86_64"
SuSE-release:
SUSE Linux Enterprise Server 11 (x86_64)
VERSION = 11
PATCHLEVEL = 1

I wish I'd been able to participate in improving the changes that were
temporarily accepted, so that ease of installation had been maintained.

**Comment by aboe76** [comment] 2013-09-25 20:04
I think this one can be closed??

**Comment by s0undt3ch** [comment] 2013-09-25 20:19
SLES 11 reached it's end of life?

**Comment by aboe76** [comment] 2013-09-25 20:21
No but the issue is 6 months old
Op 25 sep. 2013 22:20 schreef "Pedro Algarvio" notifications@github.com
het volgende:

**Comment by s0undt3ch** [comment] 2013-09-25 20:31
True. Closing. Please reopen if necessary.

**Closed as completed by s0undt3ch** 2013-09-25 20:31 UTC
