### ISSUE TITLE
Bootstrap broken on FreeBSD 9

### ISSUE THREAD

**Issue by basepi** [saltstack/salt-bootstrap#107] opened 2013-04-11 23:12 UTC
Spun up a fresh vps on Rackspace with FreeBSD 9.  Ran

```
fetch -o - http://bootstrap.saltstack.org | sh
```

The output:

```
cmyers-test# fetch -o - http://bootstrap.saltstack.org | sh
-                                               0% of   88 kB    0  Bps *  INFO: PIPED THROUGH sh -- Version 1.5.3

 *  INFO: System Information:
 *  INFO:   CPU:          AMD Opteron(tm) Processor 4170 HE
 *  INFO:   CPU Arch:     amd64
 *  INFO:   OS Name:      FreeBSD
 *  INFO:   OS Version:   9.0-RELEASE
 *  INFO:   Distribution: FreeBSD 9.0

 *  INFO: Installing minion
-                                             100% of   88 kB  763 kBps
 *  INFO: Found function install_freebsd_9_stable_deps
 *  INFO: Found function install_freebsd_9_stable
 *  INFO: Found function install_freebsd_9_stable_post
 *  INFO: Found function install_freebsd_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Running install_freebsd_9_stable_deps()
PACKAGESITE: parameter not set
```

**Comment by s0undt3ch** [comment] 2013-04-12 10:31
Although the error is not a explicit as it should, that's exactly what is supposed to happen if you don't have that variable set.

Closing it in favor of/as a duplicate of #20.

**Closed as completed by s0undt3ch** 2013-04-12 10:31 UTC

**Comment by s0undt3ch** [comment] 2013-04-12 11:39
This however, allowed for a bug to be found, see ee829cb60b411c50dfcf5aaebceb4d98eec46ccd. Thanks @basepi.

**Comment by basepi** [comment] 2013-04-12 15:39
Heh, don't thank me, thank the bug over on salt that made me boot a FreeBSD
VM.  It was not a good experience.  I couldn't get it to do ANYTHING.

So what should I have set that variable to?  I fell back on bootstrap when
I couldn't get `pkg_add` to install ANYTHING.

**Comment by s0undt3ch** [comment] 2013-04-12 17:39
Well, Salt Stack is supposed to provide FreeBSD hosting for it's FreeBSD packages and required dependencies in a "near" future. But it's on a TODO list which gets bigger and bigger. Some FreeBSD salt users have already said they'd create the packages.
