### ISSUE TITLE
Specify version of salt to install

### ISSUE THREAD

**Issue by dlindquist** [saltstack/salt-bootstrap#48] opened 2013-02-12 01:56 UTC
Since the docs say that the master needs to be upgraded before the minions, it seems that always installing the latest stable minion isn't always what is needed.  Would it be possible to specify a specific salt-minion version to install?

**Comment by s0undt3ch** [comment] 2013-02-12 21:46
This is a reasonable request. We'll see what can be done.

## 

Pedro Algarvio

----- Reply message -----

**Comment by akoumjian** [comment] 2013-02-12 21:51
Part of the problem is that most of the package managers don't even keep multiple versions at this point (I know this is a pain point for me on Ubuntu). So even if we could add it a uniform way to specify version, this kind of install couldn't be done through the various package managers.

Currently the only real way to consistently install a specific version is by using the git install and specifying a version using the git tag.

**Comment by s0undt3ch** [comment] 2013-02-12 22:06
@akoumjian Thanks for stepping in, I did not though of that :)

**Comment by s0undt3ch** [comment] 2013-02-13 16:45
Closing this since we seem to be unable to properly support this across distributions.

**Closed as completed by s0undt3ch** 2013-02-13 16:45 UTC
Labels: Feature
