### ISSUE TITLE
bootstrap script is not available

### ISSUE THREAD

**Issue by albdv** [saltstack/salt-bootstrap#701] opened 2015-12-04 19:11 UTC
Faced with an issue when bootstarp script is not available.
Could you please fix that somehow?

![screenshot from 2015-12-04 19-57-26](https://cloud.githubusercontent.com/assets/8123372/11598562/f8faf9a0-9ac2-11e5-9de7-acdd30e62509.png)

At first time see the issue at 6:10 pm utc+2 and still(8:10 pm utc+2) got the same.

**Comment by jtchoi** [comment] 2015-12-04 21:35
Seems to be working again

**Comment by wolfpackmars2** [comment] 2015-12-07 09:27
Could also link directly to the current git version of the script in case the redirect is ever down:

https://raw.githubusercontent.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh

Confirmed that the redirect link is working at this moment.

**Comment by albdv** [comment] 2015-12-07 12:02
some software like packer is using bootstrap.saltstack.com to bootstrap salt and to change the source of the shell bootstrap script is not an option in that case.
I believe right now issue might be closed.

**Comment by s0undt3ch** [comment] 2015-12-07 12:53
We have redirected DNS directly to GitHub before, however, we've had some SSL certificate complaints when doing that.

To avoid all those valid complaints, we now host a copy of the script(stable and develop versions) ourselves.

This work is being done by our distribution repositories hosting infrastructure which is still being actively developed to avoid failures like the one reported here.

Since this specific incident is now resolved, I'm closing the ticket... Please reopen or comment if you think otherwise. Thanks!

**Closed as completed** 2015-12-07 12:53 UTC
