### ISSUE TITLE
FreeBSD seems to be broken on EC2

### ISSUE THREAD

**Issue by techhat** [saltstack/salt-bootstrap#20] opened 2013-01-17 21:40 UTC
Trying to spin up a VM on AWS EC2 using salt-cloud, using the following salt-cloud profile:

aws-freebsd:
    provider: aws
    image: ami-1d4c9874
    size: Micro Instance
    script: bootstrap-salt-minion
    ssh_username: root
    sudo: False

In this configuration, the script is uploaded as /tmp/deploy.sh, and executed with:

/tmp/deploy.sh -c /tmp

When it tries to run, I get:

/tmp/deploy.sh: Command not found.

When I edit the script and change the first line to use sh instead of bash, it executes. But then it fails to load all of the packages:
- System Information:
   CPU:          Intel(R) Xeon(R) CPU           E5645  @ 2.40GHz
   CPU Arch:     amd64
   OS Name:      FreeBSD
   OS Version:   9.0-RELEASE
   Distribution: FreeBSD 9.0
- INFO: Found function install_freebsd_90_stable_deps
- INFO: Found function install_freebsd_90_stable
- INFO: config_freebsd_90_stable_minion not found....
- INFO: config_freebsd_90_minon not found....
- INFO: config_freebsd_stable_minion not found....
- INFO: config_freebsd_minion not found....
- INFO: Found function config_minion
- INFO: Found function install_freebsd_90_stable_post
- Running install_freebsd_90_stable_deps()
  pkg.txz                                               1690 kB 1143 kBps
  Installing pkg-1.0.2...pkg-1.0.2 already installed

Failed to install the following 1 package(s): ./pkg.txz
Conversion has been successfully finished
Your old packages database has been moved to: /var/db/pkg.bak.
Updating repository catalogue
Repository catalogue is up-to-date, no need to fetch fresh copy
pkg: Package 'swig' was not found in the repositories
- Failed to run install_freebsd_90_stable_deps()!!!
- Removing the logging pipe /tmp/bootstrap-salt-minion.logpipe
- Killing logging pipe tee's with pid(s): 1092

**Comment by akoumjian** [comment] 2013-01-17 21:53
Not sure why it got switched to bash, should be sh at the top.

Don't know anything about freebsd packaging, unfortunately. Looks like @cedwards might know something.

**Comment by s0undt3ch** [comment] 2013-01-17 22:03
Yes, `sh` should be at the top.

**Comment by s0undt3ch** [comment] 2013-01-17 22:04
@techhat about the packages not found, look at @akoumjian's reply

**Comment by ghost** [comment] 2013-01-17 23:00
These should all be /bin/sh, not 'bash'.

**Comment by akoumjian** [comment] 2013-01-17 23:03
@seanchannel We were talking specifically about salt-bootstrap, but assuming the current salt-cloud scripts are bourne shell compliant that should work.

**Comment by s0undt3ch** [comment] 2013-01-18 00:22
I think I know why that changed to bash. Because it's useful on some distros and because the script I usually call it like `sh ./bootstrap-salt-minion.sh` meaning that the shebang won't have an effect.

Since the script has the execution bit set by salt-cloud and is executed directly, it expects a bash binary or a simlink from the `/bin/bash` to the system's chosen `sh`.

Either way, let's change it to plain `sh`.

**Comment by techhat** [comment] 2013-01-18 00:32
We still need to do something about the second part of this issue. It would seem that the culprit may be the pkgbeta URL, which points to a server that was recently re-imaged, and may not have all of the packages that it used to. @cedwards has kindly offered his server, but I don't want him to get hammered by official Salt scripts. Is there another we could use?

**Comment by s0undt3ch** [comment] 2013-01-18 00:40
@techhat sorry, closed the script on the commit message.

**Comment by techhat** [comment] 2013-01-18 00:42
@s0undt3ch, no worries.

**Comment by s0undt3ch** [comment] 2013-01-18 00:44
@techhat I though we were already using @cedwards mirror, guess, not. I'm not that acquainted with FreeBSD so, I must allow a more familiar person to reply the your last question.

**Comment by geoffgarside** [comment] 2013-02-04 20:46
It's also probably worth noting that the sysutils/salt port has been renamed to sysutils/py-salt so when the pkgng servers get going again the package to install will be py-salt rather than salt. The name was changed to bring it in line with other python ports.

**Comment by davidblewett** [comment] 2013-05-31 03:15
The real issue is in the middle of this output:

Installing pkg-1.0.2...pkg-1.0.2 already installed

The problem is that the freebsd-specific bits in the bootstrap script all try to unconditionally install pkg. If someone is already using pkgng, however, this command will fail:

```
./pkg-static add ./pkg.txz || return 1
```

If the assumption is that pkgng _must not_ be in use yet, that should be made explicit in the documentation.

Again, this isn't specific to EC2; any FreeBSD host with an existing pkgng setup will bail here.

**Comment by geoffgarside** [comment] 2013-05-31 10:52
FreeBSD 9.1 includes a pkg bootstrapper in `/usr/sbin/pkg`, if `/usr/local/sbin/pkg` doesn't exist then it prompts to install it, if it does exist then I think it uses exec(3) to load the full version. So what we could do is use `test ! -x /usr/local/sbin/pkg` to see if pkg has already been installed and then skip the `./pkg-static` stuff in that case.

**Comment by s0undt3ch** [comment] 2013-05-31 11:01
Guys! :raised_hands: You seem to know what you're doin' as opposed to me. I just wish we'd have FreeBSD bootstrappable... :smile:

**Comment by geoffgarside** [comment] 2013-05-31 12:06
This still doesn't solve the problem of the FreeBSD pkgng servers lacking anything besides pkg on them, but based on current reports from the ports infrastructure guys it sounds like we should have 9.1 on the PACKAGESITE in the _near_ future, though how near that actually is I've no idea.

**Comment by s0undt3ch** [comment] 2013-05-31 12:38
We can't still bootstrap salt without a custom `PACKAGESITE` right?
Can anyone point me to a valid `PACKAGESITE`, so I can add FreeBSD to out buildbot setup being hacked [here](http://bootstrap.bb.ufsoft.org/waterfall)?
It will only be used for testing, not for inclusion the the script since it might be on a personal server and we don't want to hammer it with requests ;)

**Comment by geoffgarside** [comment] 2013-05-31 12:40
You can use http://pkg.geoffgarside.co.uk/freebsd:9:x86:64 for FreeBSD 9.1 packages, salt is included, updated randomly, firewall is a bit hostile, let me know if you have any trouble with it.

**Comment by s0undt3ch** [comment] 2013-05-31 13:05
Thanks!!!

Will setup a buildbot slave for FreeBSD as soon as I get home.

## 

Pedro Algarvio @ phone

----- Reply message -----
De: "Geoff Garside" notifications@github.com
Para: "saltstack/salt-bootstrap" salt-bootstrap@noreply.github.com
Cc: "Pedro Algarvio" pedro@algarvio.me
Assunto: [salt-bootstrap] FreeBSD seems to be broken on EC2 (#20)
Data: sex, Mai 31, 2013 13:40
You can use http://pkg.geoffgarside.co.uk/freebsd:9:x86:64 for FreeBSD 9.1 packages, salt is included, updated randomly 

&mdash;

**Comment by davidblewett** [comment] 2013-05-31 13:12
PC-BSD maintains a package repo for 9.1:

http://blog.pcbsd.org/2013/04/pc-bsd-announces-package-repository-for-pc-bsd-and-freebsd-9-1-release/

**Comment by davidblewett** [comment] 2013-06-04 13:56
This pull request fixes my problem: https://github.com/saltstack/salt-bootstrap/pull/151 . Now if only the PC-BSD repo would update the py-salt package  (0.14 is broken).

**Comment by s0undt3ch** [comment] 2013-06-04 15:04
@davidblewett Nice! You install from git, pass `git v0.15.3` for latest stable

**Comment by s0undt3ch** [comment] 2013-09-25 19:17
The current develop version of the bootstrap script has a greatly improved FreeBSD support.
It installs pacakges from the PCB repository if no other is defined under `PACKAGESITE`.
Salt packages are installed from http://freebsd.saltstack.com/

The develop version will be the current stable pretty soon, so, I'm closing this ticket. Please reopen if necessary.

**Closed as completed by s0undt3ch** 2013-09-25 19:17 UTC
