### ISSUE TITLE
install_salt failing to finish

### ISSUE THREAD

**Issue by doberloh** [saltstack/salt-bootstrap#935] opened 2016-08-15 22:28 UTC
Im getting failed salt installs on fresh 14.04 machines as of this afternoon Im downloading from bootstrap.saltstack.com and then running 'sudo sh install_salt.sh -P git v2015.8.8.2':

The directory '/home/ubuntu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ubuntu/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Invalid requirement: '>='
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 77, in **init**
    req = pkg_resources.Requirement.parse(req)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 3036, in parse
    req, = parse_requirements(s)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 2967, in parse_requirements
    raise RequirementParseError("Missing distribution spec", line)
RequirementParseError: Missing distribution spec >=

/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
- ERROR: Failed to run install_ubuntu_git_deps()!!!

**Comment by rallytime** [comment] 2016-08-15 22:47
@doberloh Can you post what the output of of `sh install_salt.sh -v` is? Also, has this method of installing worked for you before (i.e. is this a regression)? 

There was some refactoring done in the bootstrap script recently by @vutny and I wonder if that is causing some trouble here when using the `-P` with `sudo`. @vutny Would you mind taking a look here?

**Comment by rallytime** [comment] 2016-08-15 23:10
I was able to reproduce this error using release tags from the 2015.8 branch (tested on `v2015.8.8.2` and `v2015.8.1``) but I am unable to reproduce on more recent/stable versions of Salt on the 2016.3 branch.

Here's my stacktrace (similar, but slightly different without the `sudo` option:

```
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 257, in run
    InstallRequirement.from_line(name, None))
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 173, in from_line
    return cls(req, comes_from, url=url, prereleases=prereleases)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 71, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2667, in parse
    reqs = list(parse_requirements(s))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2593, in parse_requirements
    raise ValueError("Missing distribution spec", line)
ValueError: ('Missing distribution spec', '>=')

Storing debug log for failure in /root/.pip/pip.log
 * ERROR: Failed to run install_ubuntu_git_deps()!!!
```

This was using the most recent release from today: 2016.08.15.

**Comment by ytjohn** [comment] 2016-08-16 15:12
I started running into this yesterday as well (2016.08.15 ~4PM Eastern) when testing our salt formula in vagrant.  It's easily reproducible with Vagrant.

In an empty directory, create the following 2 files and run vagrant up.

_minion_

```
master: localhost
file_client: local

file_roots:
  base:
    - /srv/salt/
    - /srv/formulas
```

_Vagrantfile_

```
Vagrant.configure(2) do |config|

config.vm.box = "ubuntu/trusty64"

salt_install_args = '-g https://github.com/saltstack/salt.git git v2015.8.0'
 config.vm.define :test01 do |test01|
    test01.vm.provision :salt do |salt|
      salt.minion_config = 'minion'
      salt.install_master = false
      salt.run_highstate = false
      salt.verbose = true
      salt.install_args = salt_install_args
      salt.bootstrap_options = "-F -P -c /tmp" # Vagrant issue #6029 and #5973
    end
 end 
end
```

Traceback:

```
Processing triggers for libc-bin (2.19-0ubuntu6.7) ...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 257, in run
    InstallRequirement.from_line(name, None))
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 173, in from_line
    return cls(req, comes_from, url=url, prereleases=prereleases)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 71, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2667, in parse
    reqs = list(parse_requirements(s))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2593, in parse_requirements
    raise ValueError("Missing distribution spec", line)
ValueError: ('Missing distribution spec', '>=')

```

**Comment by vutny** [comment] 2016-08-16 15:14
Hi, I think I know what's going on here. Trying to fix it now. I will submit a PR soon.

**Comment by ytjohn** [comment] 2016-08-16 15:15
It might be related to pip 8.1.1 bugs: https://github.com/pypa/pip/issues/3666  https://github.com/pypa/pip/issues/3667

**Comment by vutny** [comment] 2016-08-16 15:17
Nope, it's shell expansion issue. But I'm gonna try to get rid of installing via `pip`. SaltStack has all dependencies present in their repo.

**Comment by rallytime** [comment] 2016-08-16 15:22
Thanks @vutny!

**Comment by rallytime** [comment] 2016-08-16 15:31
Also, for completeness, I tested this on the previous stable version, and this is indeed a regression with the latest stable.

**Comment by vutny** [comment] 2016-08-16 15:37
Got this fixed in #936 . Welcome to test!

**Comment by vutny** [comment] 2016-08-16 15:58
Just make sure you grabbed latest version of the script from the PR above.
https://github.com/vutny/salt-bootstrap/raw/fix-ubuntu-git-pip/bootstrap-salt.sh

**Comment by rallytime** [comment] 2016-08-16 17:04
This is fixed by #936. This fix is available in the latest release of the bootstrap script, which was just tagged as `v2016.08.16` and will be available at bootstrap.saltstack.com later today. Thanks everyone!

**Closed as completed by rallytime** 2016-08-16 17:04 UTC
Labels: Bug, Regression

**Comment by ytjohn** [comment] 2016-08-16 17:39
salt vagrant provisioner is working again, thanks!

**Comment by doberloh** [comment] 2016-08-16 18:30
Woah. I totally missed the whole train... Sorry i was unable to get more info sent in. Im testing now to see if its fixed on my end.
