### ISSUE TITLE
Automate installing apache-libcloud

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt-bootstrap#308] opened 2014-02-16 12:18 UTC
It would be awesome for this to automate installing apache-libcloud if you added in something like -C.

This way I could have libcloud installed already and can use jinja2 with cloud.query right away and put them in startup_states: highstate

Thanks,
Daniel Wallace

**Comment by s0undt3ch** [comment] 2014-02-16 12:57
Closing as a duplicate of #278

**Closed as completed by s0undt3ch** 2014-02-16 12:57 UTC
