### ISSUE TITLE
Get a Install Failed if I have installed `pyyaml`

### ISSUE THREAD

**Issue by yishenggudou** [saltstack/salt-bootstrap#258] opened 2013-11-01 03:55 UTC
```
Installed:
  m2crypto.x86_64 0:0.20.2-9.el6        python-crypto.x86_64 0:2.0.1-22.el6
  python-jinja2.x86_64 0:2.2.1-1.el6    python-msgpack.x86_64 0:0.1.13-3.el6
  python-zmq.x86_64 0:2.2.0.1-1.el6

Dependency Installed:
  libyaml.x86_64 0:0.1.3-1.el6              openpgm.x86_64 0:5.1.118-3.el6
  python-babel.noarch 0:0.9.4-5.1.el6       zeromq3.x86_64 0:3.2.4-1.el6

Failed:
  PyYAML.x86_64 0:3.10-3.el6

Complete!
 * ERROR: Failed to run install_centos_stable_deps()!!!
```

**Comment by yishenggudou** [comment] 2013-11-01 04:01
need uninstall `PyYaml`

**Comment by s0undt3ch** [comment] 2013-11-01 10:18
Could you please paste the full output of the script? Pass -D to the script too.

This will help me identify what the problem is a little faster.

Thanks!

## 

Pedro Algarvio @ phone

----- Reply message -----
De: "timger" notifications@github.com
Para: "saltstack/salt-bootstrap" salt-bootstrap@noreply.github.com
Assunto: [salt-bootstrap] Get a Install Failed if I have installed `pyyaml` (#258)
Data: sex, Nov 1, 2013 04:01
need uninstall PyYaml 

&mdash;

**Comment by s0undt3ch** [comment] 2014-02-16 20:14
No additional information was provided. Closing. Please reopen if need be.

**Closed as completed by s0undt3ch** 2014-02-16 20:14 UTC

**Comment by disylee** [comment] 2014-11-07 08:38
ERROR: Failed to run install_centos_stable_deps()!!!
this error doesn't  occure by the dependencies.but the epel didn't match it,
Solve:I try to   rpm -e epel-release-6-8.noarch
then   rpm -Uvh epel-release-6-8.noarch.rpm
last      wget -O - https://bootstrap.saltstack.com | sudo sh

solve it!!!

**Comment by s0undt3ch** [comment] 2014-11-08 09:14
@disylee what version of the bootstrap script are you using? This should have no problems on the latest stable version.
