### ISSUE TITLE
How to Remove SaltStack from Centos 8

### ISSUE THREAD

**Issue by myjewels** [saltstack/salt-bootstrap#1492] opened 2020-08-11 10:45 UTC
### Description of Issue/Question
I installed SaltStack on my CentOS 8 machine using this bootstrap script but could not figure out how to uninstall it. I need instructions on how to uninstall SaltStrck from CentOS 8 since the "**yum list installed**" command does not show any package related to salt.
### Setup
I used the following commands to install SaltStack:
curl -o bootstrap-salt.sh -L https://bootstrap.saltstack.com
sh bootstrap-salt.sh git master

### Steps to Reproduce Issue

yum list installed | egrep -i salt

### Versions and Systems

Salt Version:
           Salt: 3001-n/a-4ebd81b
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.2
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 1.0.0
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: Not Installed
   pycryptodome: 3.9.8
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr 16 2020, 01:36:27)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 19.0.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: centos 8 Core
         locale: UTF-8
        machine: x86_64
        release: 4.18.0-193.6.3.el8_2.x86_64
         system: Linux
        version: CentOS Linux 8 Core
bootstrap-salt.sh -- Version 2020.06.23
(`salt --versions-report`, `bootstrap-salt.sh -v`, system type and version,
cloud/VM provider as appropriate.)

**Comment by dmurphy18** [comment] 2020-08-11 14:35
The bootstrap command you used  is most likely to have pip installed it given that you do not find it in the yum repository and
```
Salt: 3001-n/a-4ebd81b
```
is not a released package version.  

Use **_pip3 uninstall_** to remove it.

**_pip3 list | grep -i salt_** should show the names to uninstall, in case you also installed other salt components.

If this resolves your issue, please consider closing it.

**Comment by myjewels** [comment] 2020-08-11 23:00
Thank you @dmurphy18 for your reply. I tried to uninstalled Salt as you suggested. Salt is uninstalled now but there is still a problem. Here is the output of the "pip3 list" command:

```
[root@centos8 ~]# pip3 list | grep -i salt
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
salt (3001.1)
```
So I tried to uninstall salt as shown below:

```
[root@centos8 ~]# pip3 uninstall salt

```
It looks like it worked! I rebooted the server after uninstalling salt as shown above, but systemd still tried to load salt services as shown below:
```
[root@centos8 ~]# systemctl | grep -i salt
● salt-master.service                                                                       loaded failed failed    The Salt Master Server 
● salt-minion.service                                                                       loaded failed failed    The Salt Minion
● salt-syndic.service                                                                       loaded failed failed    The Salt Master Server 
```
**It does not look like a clean uninstall. Any solution for this?**

**Comment by bryceml** [comment] 2020-08-18 15:37
with pip uninstalling, there probably isn't a cleaner solution than doing
```bash
sudo find /|grep -i salt
```
and removing relevant files in order to get all of the service/config/log/etc. files.

**Comment by barbaricyawps** [comment] 2022-01-24 19:57
This issue is related to: https://github.com/saltstack/salt-bootstrap/issues/1452

**Comment by dmurphy18** [comment] 2024-07-16 17:29
@myjewels Closing this as duplicate of https://github.com/saltstack/salt-bootstrap/issues/1844, will handle it with that feature request

**Closed as completed by dmurphy18** 2024-07-16 17:29 UTC
Labels: Question, Documentation, Duplicate, severity-medium, time-estimate-sprint
