### ISSUE TITLE
Fail to bootstrap Ubuntu 14.04

### ISSUE THREAD

**Issue by alfredopalhares** [saltstack/salt-bootstrap#690] opened 2015-11-12 17:18 UTC
Hello,

Currently its not possible to bootstrap 14.04 Ubuntu machines:

```
vagrant@default-ubuntu-1404-i386:~$ curl -L https://bootstrap.saltstack.com | sudo sh -s -- -P 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   263  100   263    0     0    334      0 --:--:-- --:--:-- --:--:--   334
 *  INFO: PIPED THROUGH sh -- Version 2015.11.09
 14  209k   14 31535    0     0  22505      0  0:00:09  0:00:01  0:00:08 22505
 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     i686
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   3.13.0-24-generic
 *  INFO:   Distribution: Ubuntu 14.04

 *  INFO: Installing minion
100  209k  100  209k    0     0   110k      0  0:00:01  0:00:01 --:--:--  362k
 *  INFO: Found function install_ubuntu_stable_deps
 *  INFO: Found function install_ubuntu_stable
 *  INFO: Found function install_ubuntu_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Found function install_ubuntu_check_services
 *  INFO: Running install_ubuntu_stable_deps()
Hit http://security.ubuntu.com trusty-security InRelease
Ign http://us.archive.ubuntu.com trusty InRelease
Hit http://repo.saltstack.com trusty InRelease
Hit http://security.ubuntu.com trusty-security/main Sources
Hit http://us.archive.ubuntu.com trusty-updates InRelease
Hit http://repo.saltstack.com trusty/main i386 Packages
Hit http://security.ubuntu.com trusty-security/restricted Sources
Hit http://us.archive.ubuntu.com trusty-backports InRelease
Hit http://security.ubuntu.com trusty-security/universe Sources
Hit http://us.archive.ubuntu.com trusty Release.gpg
Hit http://security.ubuntu.com trusty-security/multiverse Sources
Hit http://us.archive.ubuntu.com trusty-updates/main Sources
Hit http://security.ubuntu.com trusty-security/main i386 Packages
Hit http://us.archive.ubuntu.com trusty-updates/restricted Sources
Hit http://security.ubuntu.com trusty-security/restricted i386 Packages
Hit http://us.archive.ubuntu.com trusty-updates/universe Sources
Hit http://security.ubuntu.com trusty-security/universe i386 Packages
Hit http://us.archive.ubuntu.com trusty-updates/multiverse Sources
Hit http://security.ubuntu.com trusty-security/multiverse i386 Packages
Hit http://us.archive.ubuntu.com trusty-updates/main i386 Packages
Hit http://security.ubuntu.com trusty-security/main Translation-en
Hit http://us.archive.ubuntu.com trusty-updates/restricted i386 Packages
Hit http://security.ubuntu.com trusty-security/multiverse Translation-en
Ign http://repo.saltstack.com trusty/main Translation-en_US
Hit http://us.archive.ubuntu.com trusty-updates/universe i386 Packages
Hit http://security.ubuntu.com trusty-security/restricted Translation-en
Ign http://repo.saltstack.com trusty/main Translation-en
Hit http://us.archive.ubuntu.com trusty-updates/multiverse i386 Packages
Hit http://security.ubuntu.com trusty-security/universe Translation-en
Hit http://us.archive.ubuntu.com trusty-updates/main Translation-en
Hit http://us.archive.ubuntu.com trusty-updates/multiverse Translation-en
Hit http://us.archive.ubuntu.com trusty-updates/restricted Translation-en
Hit http://us.archive.ubuntu.com trusty-updates/universe Translation-en
Hit http://us.archive.ubuntu.com trusty-backports/main Sources
Hit http://us.archive.ubuntu.com trusty-backports/restricted Sources
Hit http://us.archive.ubuntu.com trusty-backports/universe Sources
Hit http://us.archive.ubuntu.com trusty-backports/multiverse Sources
Hit http://us.archive.ubuntu.com trusty-backports/main i386 Packages
Hit http://us.archive.ubuntu.com trusty-backports/restricted i386 Packages
Hit http://us.archive.ubuntu.com trusty-backports/universe i386 Packages
Hit http://us.archive.ubuntu.com trusty-backports/multiverse i386 Packages
Hit http://us.archive.ubuntu.com trusty-backports/main Translation-en
Hit http://us.archive.ubuntu.com trusty-backports/multiverse Translation-en
Hit http://us.archive.ubuntu.com trusty-backports/restricted Translation-en
Hit http://us.archive.ubuntu.com trusty-backports/universe Translation-en
Hit http://us.archive.ubuntu.com trusty Release
Hit http://us.archive.ubuntu.com trusty/main Sources
Hit http://us.archive.ubuntu.com trusty/restricted Sources
Hit http://us.archive.ubuntu.com trusty/universe Sources
Hit http://us.archive.ubuntu.com trusty/multiverse Sources
Hit http://us.archive.ubuntu.com trusty/main i386 Packages
Hit http://us.archive.ubuntu.com trusty/restricted i386 Packages
Hit http://us.archive.ubuntu.com trusty/universe i386 Packages
Hit http://us.archive.ubuntu.com trusty/multiverse i386 Packages
Hit http://us.archive.ubuntu.com trusty/main Translation-en
Hit http://us.archive.ubuntu.com trusty/multiverse Translation-en
Hit http://us.archive.ubuntu.com trusty/restricted Translation-en
Hit http://us.archive.ubuntu.com trusty/universe Translation-en
Ign http://us.archive.ubuntu.com trusty/main Translation-en_US
Ign http://us.archive.ubuntu.com trusty/multiverse Translation-en_US
Ign http://us.archive.ubuntu.com trusty/restricted Translation-en_US
Ign http://us.archive.ubuntu.com trusty/universe Translation-en_US
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
debian-archive-keyring is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 159 not upgraded.
Ign http://us.archive.ubuntu.com trusty InRelease
Hit http://security.ubuntu.com trusty-security InRelease
Hit http://repo.saltstack.com trusty InRelease
Hit http://us.archive.ubuntu.com trusty-updates InRelease
Hit http://us.archive.ubuntu.com trusty-backports InRelease
Hit http://security.ubuntu.com trusty-security/main Sources
Hit http://repo.saltstack.com trusty/main i386 Packages
Hit http://us.archive.ubuntu.com trusty Release.gpg
Hit http://security.ubuntu.com trusty-security/restricted Sources
Hit http://us.archive.ubuntu.com trusty-updates/main Sources
Hit http://security.ubuntu.com trusty-security/universe Sources
Hit http://us.archive.ubuntu.com trusty-updates/restricted Sources
Hit http://security.ubuntu.com trusty-security/multiverse Sources
Hit http://us.archive.ubuntu.com trusty-updates/universe Sources
Hit http://security.ubuntu.com trusty-security/main i386 Packages
Hit http://us.archive.ubuntu.com trusty-updates/multiverse Sources
Hit http://us.archive.ubuntu.com trusty-updates/main i386 Packages
Hit http://security.ubuntu.com trusty-security/restricted i386 Packages
Hit http://security.ubuntu.com trusty-security/universe i386 Packages
Hit http://us.archive.ubuntu.com trusty-updates/restricted i386 Packages
Hit http://security.ubuntu.com trusty-security/multiverse i386 Packages
Hit http://us.archive.ubuntu.com trusty-updates/universe i386 Packages
Hit http://security.ubuntu.com trusty-security/main Translation-en
Hit http://us.archive.ubuntu.com trusty-updates/multiverse i386 Packages
Hit http://security.ubuntu.com trusty-security/multiverse Translation-en
Hit http://us.archive.ubuntu.com trusty-updates/main Translation-en
Hit http://security.ubuntu.com trusty-security/restricted Translation-en
Hit http://us.archive.ubuntu.com trusty-updates/multiverse Translation-en
Hit http://security.ubuntu.com trusty-security/universe Translation-en
Hit http://us.archive.ubuntu.com trusty-updates/restricted Translation-en
Ign http://repo.saltstack.com trusty/main Translation-en_US
Hit http://us.archive.ubuntu.com trusty-updates/universe Translation-en
Ign http://repo.saltstack.com trusty/main Translation-en
Hit http://us.archive.ubuntu.com trusty-backports/main Sources
Hit http://us.archive.ubuntu.com trusty-backports/restricted Sources
Hit http://us.archive.ubuntu.com trusty-backports/universe Sources
Hit http://us.archive.ubuntu.com trusty-backports/multiverse Sources
Hit http://us.archive.ubuntu.com trusty-backports/main i386 Packages
Hit http://us.archive.ubuntu.com trusty-backports/restricted i386 Packages
Hit http://us.archive.ubuntu.com trusty-backports/universe i386 Packages
Hit http://us.archive.ubuntu.com trusty-backports/multiverse i386 Packages
Hit http://us.archive.ubuntu.com trusty-backports/main Translation-en
Hit http://us.archive.ubuntu.com trusty-backports/multiverse Translation-en
Hit http://us.archive.ubuntu.com trusty-backports/restricted Translation-en
Hit http://us.archive.ubuntu.com trusty-backports/universe Translation-en
Hit http://us.archive.ubuntu.com trusty Release
Hit http://us.archive.ubuntu.com trusty/main Sources
Hit http://us.archive.ubuntu.com trusty/restricted Sources
Hit http://us.archive.ubuntu.com trusty/universe Sources
Hit http://us.archive.ubuntu.com trusty/multiverse Sources
Hit http://us.archive.ubuntu.com trusty/main i386 Packages
Hit http://us.archive.ubuntu.com trusty/restricted i386 Packages
Hit http://us.archive.ubuntu.com trusty/universe i386 Packages
Hit http://us.archive.ubuntu.com trusty/multiverse i386 Packages
Hit http://us.archive.ubuntu.com trusty/main Translation-en
Hit http://us.archive.ubuntu.com trusty/multiverse Translation-en
Hit http://us.archive.ubuntu.com trusty/restricted Translation-en
Hit http://us.archive.ubuntu.com trusty/universe Translation-en
Ign http://us.archive.ubuntu.com trusty/main Translation-en_US
Ign http://us.archive.ubuntu.com trusty/multiverse Translation-en_US
Ign http://us.archive.ubuntu.com trusty/restricted Translation-en_US
Ign http://us.archive.ubuntu.com trusty/universe Translation-en_US
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
software-properties-common is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 159 not upgraded.
Hit http://repo.saltstack.com trusty InRelease
Ign http://us.archive.ubuntu.com trusty InRelease
Hit http://security.ubuntu.com trusty-security InRelease
Hit http://us.archive.ubuntu.com trusty-updates InRelease
Hit http://repo.saltstack.com trusty/main i386 Packages
Hit http://security.ubuntu.com trusty-security/main Sources
Hit http://us.archive.ubuntu.com trusty-backports InRelease
Hit http://security.ubuntu.com trusty-security/restricted Sources
Hit http://us.archive.ubuntu.com trusty Release.gpg
Hit http://security.ubuntu.com trusty-security/universe Sources
Hit http://us.archive.ubuntu.com trusty-updates/main Sources
Hit http://security.ubuntu.com trusty-security/multiverse Sources
Hit http://us.archive.ubuntu.com trusty-updates/restricted Sources
Hit http://security.ubuntu.com trusty-security/main i386 Packages
Hit http://us.archive.ubuntu.com trusty-updates/universe Sources
Hit http://security.ubuntu.com trusty-security/restricted i386 Packages
Hit http://us.archive.ubuntu.com trusty-updates/multiverse Sources
Hit http://security.ubuntu.com trusty-security/universe i386 Packages
Hit http://us.archive.ubuntu.com trusty-updates/main i386 Packages
Hit http://security.ubuntu.com trusty-security/multiverse i386 Packages
Hit http://us.archive.ubuntu.com trusty-updates/restricted i386 Packages
Hit http://security.ubuntu.com trusty-security/main Translation-en
Ign http://repo.saltstack.com trusty/main Translation-en_US
Hit http://us.archive.ubuntu.com trusty-updates/universe i386 Packages
Hit http://security.ubuntu.com trusty-security/multiverse Translation-en
Ign http://repo.saltstack.com trusty/main Translation-en
Hit http://us.archive.ubuntu.com trusty-updates/multiverse i386 Packages
Hit http://security.ubuntu.com trusty-security/restricted Translation-en
Hit http://us.archive.ubuntu.com trusty-updates/main Translation-en
Hit http://security.ubuntu.com trusty-security/universe Translation-en
Hit http://us.archive.ubuntu.com trusty-updates/multiverse Translation-en
Hit http://us.archive.ubuntu.com trusty-updates/restricted Translation-en
Hit http://us.archive.ubuntu.com trusty-updates/universe Translation-en
Hit http://us.archive.ubuntu.com trusty-backports/main Sources
Hit http://us.archive.ubuntu.com trusty-backports/restricted Sources
Hit http://us.archive.ubuntu.com trusty-backports/universe Sources
Hit http://us.archive.ubuntu.com trusty-backports/multiverse Sources
Hit http://us.archive.ubuntu.com trusty-backports/main i386 Packages
Hit http://us.archive.ubuntu.com trusty-backports/restricted i386 Packages
Hit http://us.archive.ubuntu.com trusty-backports/universe i386 Packages
Hit http://us.archive.ubuntu.com trusty-backports/multiverse i386 Packages
Hit http://us.archive.ubuntu.com trusty-backports/main Translation-en
Hit http://us.archive.ubuntu.com trusty-backports/multiverse Translation-en
Hit http://us.archive.ubuntu.com trusty-backports/restricted Translation-en
Hit http://us.archive.ubuntu.com trusty-backports/universe Translation-en
Hit http://us.archive.ubuntu.com trusty Release
Hit http://us.archive.ubuntu.com trusty/main Sources
Hit http://us.archive.ubuntu.com trusty/restricted Sources
Hit http://us.archive.ubuntu.com trusty/universe Sources
Hit http://us.archive.ubuntu.com trusty/multiverse Sources
Hit http://us.archive.ubuntu.com trusty/main i386 Packages
Hit http://us.archive.ubuntu.com trusty/restricted i386 Packages
Hit http://us.archive.ubuntu.com trusty/universe i386 Packages
Hit http://us.archive.ubuntu.com trusty/multiverse i386 Packages
Hit http://us.archive.ubuntu.com trusty/main Translation-en
Hit http://us.archive.ubuntu.com trusty/multiverse Translation-en
Hit http://us.archive.ubuntu.com trusty/restricted Translation-en
Hit http://us.archive.ubuntu.com trusty/universe Translation-en
Ign http://us.archive.ubuntu.com trusty/main Translation-en_US
Ign http://us.archive.ubuntu.com trusty/multiverse Translation-en_US
Ign http://us.archive.ubuntu.com trusty/restricted Translation-en_US
Ign http://us.archive.ubuntu.com trusty/universe Translation-en_US
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
pciutils is already the newest version.
procps is already the newest version.
python-apt is already the newest version.
python-requests is already the newest version.
upstart is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 159 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
wget is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 159 not upgraded.
OK
Hit http://repo.saltstack.com trusty InRelease
Ign http://us.archive.ubuntu.com trusty InRelease
Hit http://security.ubuntu.com trusty-security InRelease
Hit http://us.archive.ubuntu.com trusty-updates InRelease
Hit http://repo.saltstack.com trusty/main i386 Packages
Hit http://security.ubuntu.com trusty-security/main Sources
Hit http://us.archive.ubuntu.com trusty-backports InRelease
Hit http://security.ubuntu.com trusty-security/restricted Sources
Hit http://us.archive.ubuntu.com trusty Release.gpg
Hit http://security.ubuntu.com trusty-security/universe Sources
Hit http://us.archive.ubuntu.com trusty-updates/main Sources
Hit http://security.ubuntu.com trusty-security/multiverse Sources
Hit http://us.archive.ubuntu.com trusty-updates/restricted Sources
Hit http://security.ubuntu.com trusty-security/main i386 Packages
Hit http://us.archive.ubuntu.com trusty-updates/universe Sources
Hit http://security.ubuntu.com trusty-security/restricted i386 Packages
Hit http://us.archive.ubuntu.com trusty-updates/multiverse Sources
Hit http://security.ubuntu.com trusty-security/universe i386 Packages
Hit http://us.archive.ubuntu.com trusty-updates/main i386 Packages
Hit http://security.ubuntu.com trusty-security/multiverse i386 Packages
Hit http://us.archive.ubuntu.com trusty-updates/restricted i386 Packages
Hit http://security.ubuntu.com trusty-security/main Translation-en
Ign http://repo.saltstack.com trusty/main Translation-en_US
Hit http://us.archive.ubuntu.com trusty-updates/universe i386 Packages
Hit http://security.ubuntu.com trusty-security/multiverse Translation-en
Ign http://repo.saltstack.com trusty/main Translation-en
Hit http://us.archive.ubuntu.com trusty-updates/multiverse i386 Packages
Hit http://security.ubuntu.com trusty-security/restricted Translation-en
Hit http://us.archive.ubuntu.com trusty-updates/main Translation-en
Hit http://security.ubuntu.com trusty-security/universe Translation-en
Hit http://us.archive.ubuntu.com trusty-updates/multiverse Translation-en
Hit http://us.archive.ubuntu.com trusty-updates/restricted Translation-en
Hit http://us.archive.ubuntu.com trusty-updates/universe Translation-en
Hit http://us.archive.ubuntu.com trusty-backports/main Sources
Hit http://us.archive.ubuntu.com trusty-backports/restricted Sources
Hit http://us.archive.ubuntu.com trusty-backports/universe Sources
Hit http://us.archive.ubuntu.com trusty-backports/multiverse Sources
Hit http://us.archive.ubuntu.com trusty-backports/main i386 Packages
Hit http://us.archive.ubuntu.com trusty-backports/restricted i386 Packages
Hit http://us.archive.ubuntu.com trusty-backports/universe i386 Packages
Hit http://us.archive.ubuntu.com trusty-backports/multiverse i386 Packages
Hit http://us.archive.ubuntu.com trusty-backports/main Translation-en
Hit http://us.archive.ubuntu.com trusty-backports/multiverse Translation-en
Hit http://us.archive.ubuntu.com trusty-backports/restricted Translation-en
Hit http://us.archive.ubuntu.com trusty-backports/universe Translation-en
Hit http://us.archive.ubuntu.com trusty Release
Hit http://us.archive.ubuntu.com trusty/main Sources
Hit http://us.archive.ubuntu.com trusty/restricted Sources
Hit http://us.archive.ubuntu.com trusty/universe Sources
Hit http://us.archive.ubuntu.com trusty/multiverse Sources
Hit http://us.archive.ubuntu.com trusty/main i386 Packages
Hit http://us.archive.ubuntu.com trusty/restricted i386 Packages
Hit http://us.archive.ubuntu.com trusty/universe i386 Packages
Hit http://us.archive.ubuntu.com trusty/multiverse i386 Packages
Hit http://us.archive.ubuntu.com trusty/main Translation-en
Hit http://us.archive.ubuntu.com trusty/multiverse Translation-en
Hit http://us.archive.ubuntu.com trusty/restricted Translation-en
Hit http://us.archive.ubuntu.com trusty/universe Translation-en
Ign http://us.archive.ubuntu.com trusty/main Translation-en_US
Ign http://us.archive.ubuntu.com trusty/multiverse Translation-en_US
Ign http://us.archive.ubuntu.com trusty/restricted Translation-en_US
Ign http://us.archive.ubuntu.com trusty/universe Translation-en_US
Reading package lists...
 *  INFO: Running install_ubuntu_stable()
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 salt-minion : Depends: salt-common (= 2015.8.1+ds-1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
 * ERROR: Failed to run install_ubuntu_stable()!!!
```

**Comment by almoore** [comment] 2015-11-14 00:46
Have you tried installing using the git version? 

sh bootstrap-salt.sh -D -P git v2015.8.1

**Comment by abednarik** [comment] 2015-11-19 01:12
Same error here. Looks like is related to django version which is a dependency for salt-common.

**Comment by jfindlay** [comment] 2015-11-19 16:19
@abednarik, can you post some output that explains what you mean by django being a dependency for salt-common?  Thanks.

**Comment by abednarik** [comment] 2015-11-20 02:33
Sorry for the mistake, is related to tornado not django :(.

 After script fail, I try to install salt-minion manually for debug purpose

```
apt-get install salt-minion
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 salt-minion : Depends: salt-common (= 2015.8.1+ds-1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Looking at the repository, that version is present

```
apt-cache show salt-common | grep Version | head -n1
Version: 2015.8.1+ds-1
```

S I try to install that package to found out what's going on here

```
apt-get install  salt-common=2015.8.1+ds-1
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 salt-common : Depends: python-tornado (>= 4.2.1) but it is not going to be installed
               Recommends: python-mako but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

```
apt-cache show python-tornado | grep Version
Version: 3.1.1-1ubuntu2
```

There you have the current issue, I think. Let me know if I can provide more information or anything else I can do to solve this issue.

**Comment by alfredopalhares** [comment] 2015-11-23 11:37
@almoore Yes, the problem persists.

Same problem as @abednarik

**Comment by wolfpackmars2** [comment] 2015-12-04 07:00
One temporary workaround is to preinstall python-tornado 4 using pip
http://tutorialforlinux.com/2013/07/19/how-to-install-getting-started-with-tornado-3-python-serverframework-on-linux-ubuntu-13-04-raring-i386amd64-step-by-step-easy-guide/

Longer term fix would be to add this workaround into the bootstrap script if the Trusty repos aren't expected to update to Tornado 4.

**Comment by abednarik** [comment] 2015-12-08 02:33
Looks like this issue is fixed now. Python tornado 4.2 is now available. At least for me is working

``` bash
root@precise64:~# dpkg -l | grep tornado
ii  python-tornado                      4.2.1-1                    scalable, non-blocking web server and tools
```

**Comment by vutny** [comment] 2015-12-24 16:58
@masterkorp Could you please be so kind to close this issue if it works for you?

**Comment by computator** [comment] 2016-01-03 00:30
This is not fixed yet

```
user@host:~$ apt-cache show python-tornado | grep Version
Version: 3.1.1-1ubuntu2
```

**Comment by computator** [comment] 2016-01-03 02:05
This seems to be related to missing packages for non amd64 architectures per https://github.com/saltstack/salt/issues/27437

**Comment by vutny** [comment] 2016-02-24 16:16
Looks like this is an repository layout issue, nothing really related to the bootstrap script. Should be closed as duplicate.

**Comment by vutny** [comment] 2016-02-25 09:20
Submitted PR to reflect this in the documentation: saltstack/salt#31477

**Comment by vutny** [comment] 2016-02-25 09:31
Ping @dmurphy18

**Comment by vutny** [comment] 2016-03-11 08:49
Ping @jfindlay

**Comment by jfindlay** [comment] 2016-04-14 22:37
This seems to have been fixed with the creation of repo.saltstack.com.  If anyone is still finding problems bootstrapping 14.04, please open a new issue, thanks.

**Closed as completed by jfindlay** 2016-04-14 22:37 UTC

**Comment by ageld** [comment] 2017-05-01 18:52
pip freeze states that I do have version 4.5.1 installed:
# pip freeze | grep tornado
tornado==4.5.1

However, apt-get reports the version, which is in Ubuntu 14.04 repository:

# dpkg -l | grep tornado
ii  python-tornado                            3.1.1-1ubuntu2                             all          scalable, non-blocking web server and tools

If I remove it with apt-get remove and leave only the one installed by pip, the

apt-get install salt-common

still fails with:

The following packages have unmet dependencies:
 salt-common : Depends: python-tornado (>= 4.2.1) but it is not going to be installed

# uname -a
Linux njnprobe.usa.local 3.13.0-110-generic #157-Ubuntu SMP Mon Feb 20 11:55:25 UTC 2017 i686 i686 i686 GNU/Linux

Is there a way to point installation to the PIP installed version?

I will greatly appreciate your help!!!

**Comment by wolfpackmars2** [comment] 2017-05-04 01:06
EDIT: I just confirmed that the SaltStack repository contains the correct version of Tornado for Ubuntu 14.04. As long as you are using the bootstrapper [https://github.com/saltstack/salt-bootstrap](https://github.com/saltstack/salt-bootstrap) salt should be installed. If this is not the case, post a new issue. If you are trying to install SaltStack without the bootstrapper, you will need to add a reference to repo.saltstack.com to your apt sources. If your platform is other than Amd64 (ie not 64 bit Ubuntu or Raspbian or something else) then you will need to find a repository which supports your platform and distro and has the correct dependencies.

@ageld Are you using the bootstrapper to install Salt?  It's my understanding that the bootstrapper should configure the repositories and install the correct dependencies. I believe installing with PIP will make the libraries available for use with Python, but not the system.  The bootstrapper should add a reference to repo.saltstack.com, which should have the correct version of tornado available.  If not, try manually adding the repository. You may need to change the [repository priority](https://askubuntu.com/a/153408).

If that fails, post a new bug report for salt-bootstrap.  In the mean time, find a repository for your version of Ubuntu which contains the correct version of Tornado.

**Comment by ageld** [comment] 2017-05-08 17:41
Yes, I used bootstrapper as well as regular apt-get.  I will try to play with the priority.


Thanks a lot for help.


________________________________

**Comment by ageld** [comment] 2017-05-08 18:06
I think the problem is that the repository:


https://repo.saltstack.com/apt/ubuntu/14.04/


only has amd64 versions of software.  I, however, have 32-bit systems on which I hope to install saltstack-minion software.


Regards,


Alek Geldenberg


________________________________

**Comment by wolfpackmars2** [comment] 2017-05-09 03:48
Ok, so yes the problem is that the repositories only seem to contain 64 bit packages.

The boot strapper should still work.  I don't have personal experience with this, as I primarily only install Salt on 64 bit debian systems.

I believe this applies to your situation: https://github.com/saltstack/salt-bootstrap#supported-operating-systems

You don't need to specify "develop" - you should be able to install any branch (release version) of salt stack using this method.

Use pip as the source repository, which should install Tornado 4.5.1 from pypi.
