### ISSUE TITLE
Failure to install 3007.0 on CentOS Stream 8

### ISSUE THREAD

**Issue by witchkinkofangmar** [saltstack/salt-bootstrap#1994] opened 2024-03-27 20:51 UTC
### Description of Issue/Question
I am deploying workloads via Aria Automation (formerly vRA) and installing/configuring the salt-minion on VMs. This works for all rpm based distro's I'm using (and debian/windows) except CentOS Stream release 8. CentOS 7 works fine. Not using CentOS stream release 9 but maybe similar to this issue [1935](https://github.com/saltstack/salt-bootstrap/issues/1935)

### Setup
CentOS Stream release 8
```
[master1 cloud.deploy.d]# bash bootstrap-salt.sh -v
bootstrap-salt.sh -- Version 2024.01.04
```

### Steps to Reproduce Issue
Both automated install and manual install runs from /tmp/.saltcloud-15444871-9573-488e-8342-e76f75a966f0/deploy.sh
`bash /tmp/.saltcloud-15444871-9573-488e-8342-e76f75a966f0/deploy.sh`

```
[root@dcent8wk01 tmp]# tail -f bootstrap-salt.log
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   4.18.0-358.el8.x86_64
 *  INFO:   Distribution: CentOSStream 8

 *  INFO: Installing minion
 *  INFO: Found function config_salt
 *  INFO: Found function preseed_master
 *  INFO: Found function daemons_running_onedir
 * ERROR: No dependencies installation function found. Exiting...
```
```
[root@dcent8wk01 .saltcloud-15444871-9573-488e-8342-e76f75a966f0]# bash deploy.sh -D
 *  INFO: Running version: 2024.01.04
 *  INFO: Executed by: bash
 *  INFO: Command line: 'deploy.sh -D'

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   4.18.0-358.el8.x86_64
 *  INFO:   Distribution: CentOSStream 8

 * DEBUG: Binaries will be searched using the following $PATH: /usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
 *  INFO: Installing minion
 * DEBUG: install_centosstream_8_onedir_deps not found....
 * DEBUG: install_centosstream_8_deps not found....
 * DEBUG: install_centosstream_onedir_deps not found....
 * DEBUG: install_centosstream_deps not found....
 * DEBUG: DEPS_INSTALL_FUNC=null
 * DEBUG: config_centosstream_8_onedir_salt not found....
 * DEBUG: config_centosstream_8_salt not found....
 * DEBUG: config_centosstream_onedir_salt not found....
 * DEBUG: config_centosstream_salt not found....
 *  INFO: Found function config_salt
 * DEBUG: CONFIG_SALT_FUNC=config_salt
 * DEBUG: preseed_centosstream_8_onedir_master not found....
 * DEBUG: preseed_centosstream_8_master not found....
 * DEBUG: preseed_centosstream_onedir_master not found....
 * DEBUG: preseed_centosstream_master not found....
 *  INFO: Found function preseed_master
 * DEBUG: PRESEED_MASTER_FUNC=preseed_master
 * DEBUG: INSTALL_FUNC_NAMES=install_centosstream_8_onedir install_centosstream_8_onedir install_centosstream_onedir
 * DEBUG: install_centosstream_8_onedir not found....
 * DEBUG: install_centosstream_onedir not found....
 * DEBUG: INSTALL_FUNC=null
 * DEBUG: install_centosstream_8_onedir_post not found....
 * DEBUG: install_centosstream_8_post not found....
 * DEBUG: install_centosstream_onedir_post not found....
 * DEBUG: install_centosstream_post not found....
 * DEBUG: POST_INSTALL_FUNC=null
 * DEBUG: install_centosstream_8_onedir_restart_daemons not found....
 * DEBUG: install_centosstream_8_restart_daemons not found....
 * DEBUG: install_centosstream_onedir_restart_daemons not found....
 * DEBUG: install_centosstream_restart_daemons not found....
 * DEBUG: STARTDAEMONS_INSTALL_FUNC=null
 * DEBUG: daemons_running_centosstream_8_onedir not found....
 * DEBUG: daemons_running_centosstream_8 not found....
 * DEBUG: daemons_running_centosstream_onedir not found....
 * DEBUG: daemons_running_centosstream not found....
 *  INFO: Found function daemons_running_onedir
 * DEBUG: DAEMONS_RUNNING_FUNC=daemons_running_onedir
 * DEBUG: install_centosstream_8_onedir_check_services not found....
 * DEBUG: install_centosstream_8_check_services not found....
 * DEBUG: install_centosstream_onedir_check_services not found....
 * DEBUG: install_centosstream_check_services not found....
 * DEBUG: CHECK_SERVICES_FUNC=null
 * ERROR: No dependencies installation function found. Exiting...
 * DEBUG: Removing the logging pipe /tmp/bootstrap-salt.logpipe
 * DEBUG: Removing the temporary apt error file /tmp/apt_error.7JHGnK
 * DEBUG: Killing logging pipe tee's with pid(s): 3714
```

### Versions and Systems

```
[master01 cloud.deploy.d]# salt --versions-report
Salt Version:
          Salt: 3007.0

Python Version:
        Python: 3.10.13 (main, Feb 19 2024, 03:31:20) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.16.0
      cherrypy: unknown
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.3
       libgit2: 1.7.2
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.7
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 23.1
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: 1.14.1
  python-gnupg: 0.5.2
        PyYAML: 6.0.1
         PyZMQ: 25.1.2
        relenv: 0.15.1
         smmap: Not Installed
       timelib: 0.3.0
       Tornado: 6.3.3
           ZMQ: 4.3.4

Salt Extensions:
        SSEAPE: 8.16.1.4

Salt Package Information:
  Package Type: onedir

System Versions:
          dist: rhel 8.8 Ootpa
        locale: utf-8
       machine: x86_64
       release: 4.18.0-477.21.1.el8_8.x86_64
        system: Linux
       version: Red Hat Enterprise Linux 8.8 Ootpa
```

**Comment by witchkinkofangmar** [comment] 2024-03-28 16:10
For me, uninstalling lsb_release apparently fixes the issue. 

`yum remove -y redhat-lsb-core`

**Comment by dmurphy18** [comment] 2024-04-01 16:18
@witchkinkofangmar Wondering why this an Open Salt issue, since I can install Salt 3007.0 on Centosstream 8 fine.  This looks like a problem for Aria Config (vRA) and you lodge an issue with them.

You are installing using the bootstrap script, which has it own repository, and if an issue exists, it should be lodged against that repo, https://github.com/saltstack/salt-bootstrap. Note that is undergoing a major re-write at the moment, for better support of newer OSs and removal of old OSs (Wheezy, etc, and Python 2).

For production it is recommended that you install packaged software from repo.saltproject.io.

From the output above, I am missing the issue that you are stating, since the version report is working and shows that the salt-master for Salt 3007.0 is working,  Note: I have install Salt 3007 on Centosstream 8, AlmaLinux 8 and Rocky 8 without issue.

If the problem is 
```
 ERROR: No dependencies installation function found. Exiting...
```

Since Salt 3006.x, Salt has all dependencies self-contained, in order to allow functioning on older OSs which have EOL versions of Python, for example: Centosstream comes with Python 3.6 which is long EOL'd.

Even with redhat-lsb-core installed , I didn't notice anything wrong in the operation of Salt 3007.0

Closing this, and the issue should be addressed against vRA if a problem with vRA, or bootstrap repo if there a problem with bootstrap, but it appears that it installed Salt 3007.0.

Please feel free to re-open this issue with a detailed explanation of the problem with examples of how to reproduce the issue.

**Closed as completed by dmurphy18** 2024-04-01 16:18 UTC
Labels: Cannot Reproduce

**Comment by witchkinkofangmar** [comment] 2024-04-01 16:30
Must have been bootstrap related since installing manually works and the bootstrap works after uninstalling redhat-lsb-core

**Comment by dmurphy18** [comment] 2024-04-01 16:37
bootstrap has a number of issues, hence the re-write, and a major set of changes.  In the process of also removing kitchen-salt from the bootstrap repo to use GitHub Actions, similar to what was done with regular Salt, but it will be a while before it is ready for prime time.  I will check to make sure it works with redhat-lsb-core installed as part of the testing, see https://github.com/saltstack/salt-bootstrap/pull/1987#issuecomment-2030122286
